
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.DataBindings.DataTable MainBox;
	private global::Gtk.DataBindings.DataLabel datalabel1;
	private global::Gtk.DataBindings.DataProgressBar dataprogressbar1;
	private global::Gtk.DataBindings.DataProgressBar dataprogressbar2;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Label label6;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainBox = new global::Gtk.DataBindings.DataTable (((uint)(3)), ((uint)(2)), false);
		this.MainBox.Name = "MainBox";
		this.MainBox.RowSpacing = ((uint)(6));
		this.MainBox.ColumnSpacing = ((uint)(6));
		this.MainBox.BorderWidth = ((uint)(8));
		this.MainBox.InheritedDataSource = false;
		this.MainBox.InheritedBoundaryDataSource = false;
		this.MainBox.InheritedDataSource = false;
		this.MainBox.InheritedBoundaryDataSource = false;
		// Container child MainBox.Gtk.Table+TableChild
		this.datalabel1 = new global::Gtk.DataBindings.DataLabel ();
		this.datalabel1.Name = "datalabel1";
		this.datalabel1.Xalign = 0F;
		this.datalabel1.UseMarkup = true;
		this.datalabel1.InheritedDataSource = true;
		this.datalabel1.Mappings = "Name";
		this.datalabel1.InheritedBoundaryDataSource = false;
		this.datalabel1.Important = false;
		this.datalabel1.InheritedDataSource = true;
		this.datalabel1.Mappings = "Name";
		this.datalabel1.InheritedBoundaryDataSource = false;
		this.MainBox.Add (this.datalabel1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.MainBox [this.datalabel1]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainBox.Gtk.Table+TableChild
		this.dataprogressbar1 = new global::Gtk.DataBindings.DataProgressBar ();
		this.dataprogressbar1.Name = "dataprogressbar1";
		this.dataprogressbar1.InheritedDataSource = true;
		this.dataprogressbar1.Mappings = "FilePos";
		this.dataprogressbar1.InheritedBoundaryDataSource = false;
		this.dataprogressbar1.InheritedDataSource = true;
		this.dataprogressbar1.Mappings = "FilePos";
		this.dataprogressbar1.InheritedBoundaryDataSource = false;
		this.MainBox.Add (this.dataprogressbar1);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.MainBox [this.dataprogressbar1]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainBox.Gtk.Table+TableChild
		this.dataprogressbar2 = new global::Gtk.DataBindings.DataProgressBar ();
		this.dataprogressbar2.Name = "dataprogressbar2";
		this.dataprogressbar2.InheritedDataSource = true;
		this.dataprogressbar2.Mappings = "CopyPos";
		this.dataprogressbar2.InheritedBoundaryDataSource = false;
		this.dataprogressbar2.InheritedDataSource = true;
		this.dataprogressbar2.Mappings = "CopyPos";
		this.dataprogressbar2.InheritedBoundaryDataSource = false;
		this.MainBox.Add (this.dataprogressbar2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.MainBox [this.dataprogressbar2]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainBox.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Filename");
		this.MainBox.Add (this.label4);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.MainBox [this.label4]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainBox.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Progress");
		this.MainBox.Add (this.label5);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.MainBox [this.label5]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainBox.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Total");
		this.MainBox.Add (this.label6);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.MainBox [this.label6]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.MainBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
