// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.DataBindings.DataTable MainBox;
    
    private Gtk.DataBindings.DataLabel datalabel1;
    
    private Gtk.DataBindings.DataProgressBar dataprogressbar1;
    
    private Gtk.DataBindings.DataProgressBar dataprogressbar2;
    
    private Gtk.Label label4;
    
    private Gtk.Label label5;
    
    private Gtk.Label label6;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.Resizable = false;
        this.AllowGrow = false;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.MainBox = new Gtk.DataBindings.DataTable(((uint)(3)), ((uint)(2)), false);
        this.MainBox.Name = "MainBox";
        this.MainBox.RowSpacing = ((uint)(6));
        this.MainBox.ColumnSpacing = ((uint)(6));
        this.MainBox.BorderWidth = ((uint)(8));
        this.MainBox.InheritedDataSource = false;
        this.MainBox.InheritedBoundaryDataSource = false;
        this.MainBox.BoundaryMappings = "";
        // Container child MainBox.Gtk.Table+TableChild
        this.datalabel1 = new Gtk.DataBindings.DataLabel();
        this.datalabel1.Name = "datalabel1";
        this.datalabel1.Xalign = 0F;
        this.datalabel1.UseMarkup = true;
        this.datalabel1.InheritedDataSource = true;
        this.datalabel1.Mappings = "Name";
        this.datalabel1.InheritedBoundaryDataSource = false;
        this.datalabel1.BoundaryMappings = "";
        this.MainBox.Add(this.datalabel1);
        Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.MainBox[this.datalabel1]));
        w1.LeftAttach = ((uint)(1));
        w1.RightAttach = ((uint)(2));
        w1.XOptions = ((Gtk.AttachOptions)(4));
        w1.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainBox.Gtk.Table+TableChild
        this.dataprogressbar1 = new Gtk.DataBindings.DataProgressBar();
        this.dataprogressbar1.Name = "dataprogressbar1";
        this.dataprogressbar1.InheritedDataSource = true;
        this.dataprogressbar1.Mappings = "FilePos";
        this.dataprogressbar1.InheritedBoundaryDataSource = false;
        this.dataprogressbar1.BoundaryMappings = "";
        this.MainBox.Add(this.dataprogressbar1);
        Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.MainBox[this.dataprogressbar1]));
        w2.TopAttach = ((uint)(2));
        w2.BottomAttach = ((uint)(3));
        w2.LeftAttach = ((uint)(1));
        w2.RightAttach = ((uint)(2));
        w2.XOptions = ((Gtk.AttachOptions)(4));
        w2.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainBox.Gtk.Table+TableChild
        this.dataprogressbar2 = new Gtk.DataBindings.DataProgressBar();
        this.dataprogressbar2.Name = "dataprogressbar2";
        this.dataprogressbar2.InheritedDataSource = true;
        this.dataprogressbar2.Mappings = "CopyPos";
        this.dataprogressbar2.InheritedBoundaryDataSource = false;
        this.dataprogressbar2.BoundaryMappings = "";
        this.MainBox.Add(this.dataprogressbar2);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.MainBox[this.dataprogressbar2]));
        w3.TopAttach = ((uint)(1));
        w3.BottomAttach = ((uint)(2));
        w3.LeftAttach = ((uint)(1));
        w3.RightAttach = ((uint)(2));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainBox.Gtk.Table+TableChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.Xalign = 0F;
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Filename");
        this.MainBox.Add(this.label4);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.MainBox[this.label4]));
        w4.XOptions = ((Gtk.AttachOptions)(4));
        w4.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainBox.Gtk.Table+TableChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.Xalign = 0F;
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("Progress");
        this.MainBox.Add(this.label5);
        Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.MainBox[this.label5]));
        w5.TopAttach = ((uint)(1));
        w5.BottomAttach = ((uint)(2));
        w5.XOptions = ((Gtk.AttachOptions)(4));
        w5.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainBox.Gtk.Table+TableChild
        this.label6 = new Gtk.Label();
        this.label6.Name = "label6";
        this.label6.Xalign = 0F;
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("Total");
        this.MainBox.Add(this.label6);
        Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.MainBox[this.label6]));
        w6.TopAttach = ((uint)(2));
        w6.BottomAttach = ((uint)(3));
        w6.XOptions = ((Gtk.AttachOptions)(4));
        w6.YOptions = ((Gtk.AttachOptions)(4));
        this.Add(this.MainBox);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
