// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.DataBindings.DataHBox WindowBox;
    
    private Gtk.DataBindings.DataTable table1;
    
    private Gtk.DataBindings.DataCheckButton datacheckbutton1;
    
    private Gtk.DataBindings.DataEntry dataentry1;
    
    private Gtk.DataBindings.DataEntry dataentry2;
    
    private Gtk.DataBindings.DataEntry dataentry3;
    
    private Gtk.DataBindings.DataLabel datalabel1;
    
    private Gtk.DataBindings.DataLabel datalabel2;
    
    private Gtk.DataBindings.DataComboBoxEntry DatasetsCB;
    
    private Gtk.DataBindings.DataComboBox DriversCB;
    
    private Gtk.Label label1;
    
    private Gtk.Label label2;
    
    private Gtk.Label label3;
    
    private Gtk.Label label4;
    
    private Gtk.Label label5;
    
    private Gtk.Label label6;
    
    private Gtk.Label label7;
    
    private Gtk.Label label8;
    
    private Gtk.DataBindings.DataComboBox TablesCB;
    
    private Gtk.DataBindings.DataVBox TableViewBox;
    
    private Gtk.DataBindings.DataHBox QueryBox;
    
    private Gtk.DataBindings.DataTable QueryTable;
    
    private Gtk.DataBindings.DataEntry dataentry4;
    
    private Gtk.DataBindings.DataEntry dataentry5;
    
    private Gtk.Label label10;
    
    private Gtk.Label label9;
    
    private Gtk.Button btnRunQuery;
    
    private Gtk.Button btnColumns;
    
    private Gtk.ScrolledWindow TableView;
    
    private Gtk.DataBindings.DataTreeView treeview1;
    
    private Gtk.DataBindings.DataLabel datalabel3;
    
    private Gtk.DataBindings.DataHBox StatusBox;
    
    private Gtk.Label label11;
    
    private Gtk.DataBindings.DataLabel datalabel4;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.BorderWidth = ((uint)(8));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.WindowBox = new Gtk.DataBindings.DataHBox();
        this.WindowBox.Name = "WindowBox";
        this.WindowBox.Spacing = 6;
        this.WindowBox.InheritedDataSource = false;
        this.WindowBox.InheritedBoundaryDataSource = false;
        // Container child WindowBox.Gtk.Box+BoxChild
        this.table1 = new Gtk.DataBindings.DataTable(((uint)(11)), ((uint)(2)), false);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(8));
        this.table1.InheritedDataSource = true;
        this.table1.InheritedBoundaryDataSource = false;
        // Container child table1.Gtk.Table+TableChild
        this.datacheckbutton1 = new Gtk.DataBindings.DataCheckButton();
        this.datacheckbutton1.CanFocus = true;
        this.datacheckbutton1.Name = "datacheckbutton1";
        this.datacheckbutton1.Label = Mono.Unix.Catalog.GetString("Active");
        this.datacheckbutton1.DrawIndicator = true;
        this.datacheckbutton1.UseUnderline = true;
        this.datacheckbutton1.InheritedDataSource = true;
        this.datacheckbutton1.Mappings = "Active";
        this.datacheckbutton1.InheritedBoundaryDataSource = false;
        this.table1.Add(this.datacheckbutton1);
        Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.datacheckbutton1]));
        w1.TopAttach = ((uint)(4));
        w1.BottomAttach = ((uint)(5));
        w1.LeftAttach = ((uint)(1));
        w1.RightAttach = ((uint)(2));
        w1.XOptions = ((Gtk.AttachOptions)(4));
        w1.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.dataentry1 = new Gtk.DataBindings.DataEntry();
        this.dataentry1.CanFocus = true;
        this.dataentry1.Name = "dataentry1";
        this.dataentry1.IsEditable = true;
        this.dataentry1.InvisibleChar = '•';
        this.dataentry1.InheritedDataSource = true;
        this.dataentry1.Mappings = "Server";
        this.dataentry1.InheritedBoundaryDataSource = false;
        this.table1.Add(this.dataentry1);
        Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.dataentry1]));
        w2.TopAttach = ((uint)(1));
        w2.BottomAttach = ((uint)(2));
        w2.LeftAttach = ((uint)(1));
        w2.RightAttach = ((uint)(2));
        w2.XOptions = ((Gtk.AttachOptions)(4));
        w2.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.dataentry2 = new Gtk.DataBindings.DataEntry();
        this.dataentry2.CanFocus = true;
        this.dataentry2.Name = "dataentry2";
        this.dataentry2.IsEditable = true;
        this.dataentry2.InvisibleChar = '•';
        this.dataentry2.InheritedDataSource = true;
        this.dataentry2.Mappings = "Username";
        this.dataentry2.InheritedBoundaryDataSource = false;
        this.table1.Add(this.dataentry2);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.dataentry2]));
        w3.TopAttach = ((uint)(2));
        w3.BottomAttach = ((uint)(3));
        w3.LeftAttach = ((uint)(1));
        w3.RightAttach = ((uint)(2));
        w3.XOptions = ((Gtk.AttachOptions)(4));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.dataentry3 = new Gtk.DataBindings.DataEntry();
        this.dataentry3.CanFocus = true;
        this.dataentry3.Name = "dataentry3";
        this.dataentry3.IsEditable = true;
        this.dataentry3.Visibility = false;
        this.dataentry3.InvisibleChar = '•';
        this.dataentry3.InheritedDataSource = true;
        this.dataentry3.Mappings = "Password";
        this.dataentry3.InheritedBoundaryDataSource = false;
        this.table1.Add(this.dataentry3);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.dataentry3]));
        w4.TopAttach = ((uint)(3));
        w4.BottomAttach = ((uint)(4));
        w4.LeftAttach = ((uint)(1));
        w4.RightAttach = ((uint)(2));
        w4.XOptions = ((Gtk.AttachOptions)(4));
        w4.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.datalabel1 = new Gtk.DataBindings.DataLabel();
        this.datalabel1.Name = "datalabel1";
        this.datalabel1.Xalign = 0F;
        this.datalabel1.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
        this.datalabel1.InheritedDataSource = true;
        this.datalabel1.Mappings = "ConnectedDataset";
        this.datalabel1.InheritedBoundaryDataSource = false;
        this.table1.Add(this.datalabel1);
        Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.datalabel1]));
        w5.TopAttach = ((uint)(7));
        w5.BottomAttach = ((uint)(8));
        w5.LeftAttach = ((uint)(1));
        w5.RightAttach = ((uint)(2));
        w5.XOptions = ((Gtk.AttachOptions)(4));
        w5.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.datalabel2 = new Gtk.DataBindings.DataLabel();
        this.datalabel2.Name = "datalabel2";
        this.datalabel2.Xalign = 0F;
        this.datalabel2.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
        this.datalabel2.InheritedDataSource = true;
        this.datalabel2.Mappings = "IsActive";
        this.datalabel2.InheritedBoundaryDataSource = false;
        this.table1.Add(this.datalabel2);
        Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.datalabel2]));
        w6.TopAttach = ((uint)(5));
        w6.BottomAttach = ((uint)(6));
        w6.LeftAttach = ((uint)(1));
        w6.RightAttach = ((uint)(2));
        w6.XOptions = ((Gtk.AttachOptions)(4));
        w6.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.DatasetsCB = new Gtk.DataBindings.DataComboBoxEntry();
        this.DatasetsCB.Name = "DatasetsCB";
        this.DatasetsCB.Active = 0;
        this.DatasetsCB.InheritedDataSource = false;
        this.DatasetsCB.Mappings = "";
        this.DatasetsCB.ColumnMappings = "";
        this.DatasetsCB.InheritedBoundaryDataSource = false;
        this.table1.Add(this.DatasetsCB);
        Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.DatasetsCB]));
        w7.TopAttach = ((uint)(6));
        w7.BottomAttach = ((uint)(7));
        w7.LeftAttach = ((uint)(1));
        w7.RightAttach = ((uint)(2));
        w7.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.DriversCB = new Gtk.DataBindings.DataComboBox();
        this.DriversCB.Name = "DriversCB";
        this.DriversCB.Active = 0;
        this.DriversCB.InheritedDataSource = false;
        this.DriversCB.Mappings = "";
        this.DriversCB.ColumnMappings = "";
        this.DriversCB.InheritedBoundaryDataSource = false;
        this.table1.Add(this.DriversCB);
        Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.DriversCB]));
        w8.LeftAttach = ((uint)(1));
        w8.RightAttach = ((uint)(2));
        w8.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.Xalign = 0F;
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Connected Database");
        this.table1.Add(this.label1);
        Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
        w9.TopAttach = ((uint)(7));
        w9.BottomAttach = ((uint)(8));
        w9.XOptions = ((Gtk.AttachOptions)(4));
        w9.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.Xalign = 0F;
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Tables");
        this.table1.Add(this.label2);
        Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
        w10.TopAttach = ((uint)(8));
        w10.BottomAttach = ((uint)(9));
        w10.XOptions = ((Gtk.AttachOptions)(4));
        w10.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.Xalign = 0F;
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Server");
        this.table1.Add(this.label3);
        Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
        w11.TopAttach = ((uint)(1));
        w11.BottomAttach = ((uint)(2));
        w11.XOptions = ((Gtk.AttachOptions)(4));
        w11.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.Xalign = 0F;
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Username");
        this.table1.Add(this.label4);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
        w12.TopAttach = ((uint)(2));
        w12.BottomAttach = ((uint)(3));
        w12.XOptions = ((Gtk.AttachOptions)(4));
        w12.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.Xalign = 0F;
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("Password");
        this.table1.Add(this.label5);
        Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
        w13.TopAttach = ((uint)(3));
        w13.BottomAttach = ((uint)(4));
        w13.XOptions = ((Gtk.AttachOptions)(4));
        w13.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label6 = new Gtk.Label();
        this.label6.Name = "label6";
        this.label6.Xalign = 0F;
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("Database drivers");
        this.table1.Add(this.label6);
        Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
        w14.XOptions = ((Gtk.AttachOptions)(4));
        w14.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label7 = new Gtk.Label();
        this.label7.Name = "label7";
        this.label7.Xalign = 0F;
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("Databases");
        this.table1.Add(this.label7);
        Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
        w15.TopAttach = ((uint)(6));
        w15.BottomAttach = ((uint)(7));
        w15.XOptions = ((Gtk.AttachOptions)(4));
        w15.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.label8 = new Gtk.Label();
        this.label8.Name = "label8";
        this.label8.Xalign = 0F;
        this.label8.LabelProp = Mono.Unix.Catalog.GetString("IsActive");
        this.table1.Add(this.label8);
        Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.label8]));
        w16.TopAttach = ((uint)(5));
        w16.BottomAttach = ((uint)(6));
        w16.XOptions = ((Gtk.AttachOptions)(4));
        w16.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.TablesCB = new Gtk.DataBindings.DataComboBox();
        this.TablesCB.Name = "TablesCB";
        this.TablesCB.InheritedDataSource = false;
        this.TablesCB.InheritedBoundaryDataSource = false;
        this.table1.Add(this.TablesCB);
        Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.TablesCB]));
        w17.TopAttach = ((uint)(8));
        w17.BottomAttach = ((uint)(9));
        w17.LeftAttach = ((uint)(1));
        w17.RightAttach = ((uint)(2));
        w17.YOptions = ((Gtk.AttachOptions)(4));
        this.WindowBox.Add(this.table1);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.WindowBox[this.table1]));
        w18.Position = 0;
        w18.Expand = false;
        w18.Fill = false;
        // Container child WindowBox.Gtk.Box+BoxChild
        this.TableViewBox = new Gtk.DataBindings.DataVBox();
        this.TableViewBox.Name = "TableViewBox";
        this.TableViewBox.Spacing = 6;
        this.TableViewBox.InheritedDataSource = true;
        this.TableViewBox.InheritedBoundaryDataSource = false;
        // Container child TableViewBox.Gtk.Box+BoxChild
        this.QueryBox = new Gtk.DataBindings.DataHBox();
        this.QueryBox.Name = "QueryBox";
        this.QueryBox.Spacing = 6;
        this.QueryBox.InheritedDataSource = true;
        this.QueryBox.InheritedBoundaryDataSource = false;
        // Container child QueryBox.Gtk.Box+BoxChild
        this.QueryTable = new Gtk.DataBindings.DataTable(((uint)(2)), ((uint)(2)), false);
        this.QueryTable.Name = "QueryTable";
        this.QueryTable.RowSpacing = ((uint)(6));
        this.QueryTable.ColumnSpacing = ((uint)(6));
        this.QueryTable.InheritedDataSource = true;
        this.QueryTable.InheritedBoundaryDataSource = false;
        // Container child QueryTable.Gtk.Table+TableChild
        this.dataentry4 = new Gtk.DataBindings.DataEntry();
        this.dataentry4.CanFocus = true;
        this.dataentry4.Name = "dataentry4";
        this.dataentry4.IsEditable = true;
        this.dataentry4.InvisibleChar = '•';
        this.dataentry4.InheritedDataSource = true;
        this.dataentry4.Mappings = "Where";
        this.dataentry4.InheritedBoundaryDataSource = false;
        this.QueryTable.Add(this.dataentry4);
        Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.QueryTable[this.dataentry4]));
        w19.TopAttach = ((uint)(1));
        w19.BottomAttach = ((uint)(2));
        w19.LeftAttach = ((uint)(1));
        w19.RightAttach = ((uint)(2));
        w19.YOptions = ((Gtk.AttachOptions)(4));
        // Container child QueryTable.Gtk.Table+TableChild
        this.dataentry5 = new Gtk.DataBindings.DataEntry();
        this.dataentry5.CanFocus = true;
        this.dataentry5.Name = "dataentry5";
        this.dataentry5.IsEditable = true;
        this.dataentry5.InvisibleChar = '•';
        this.dataentry5.InheritedDataSource = true;
        this.dataentry5.Mappings = "Select";
        this.dataentry5.InheritedBoundaryDataSource = false;
        this.QueryTable.Add(this.dataentry5);
        Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.QueryTable[this.dataentry5]));
        w20.LeftAttach = ((uint)(1));
        w20.RightAttach = ((uint)(2));
        w20.YOptions = ((Gtk.AttachOptions)(4));
        // Container child QueryTable.Gtk.Table+TableChild
        this.label10 = new Gtk.Label();
        this.label10.Name = "label10";
        this.label10.Xalign = 0F;
        this.label10.LabelProp = Mono.Unix.Catalog.GetString("SELECT");
        this.QueryTable.Add(this.label10);
        Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.QueryTable[this.label10]));
        w21.XOptions = ((Gtk.AttachOptions)(4));
        w21.YOptions = ((Gtk.AttachOptions)(4));
        // Container child QueryTable.Gtk.Table+TableChild
        this.label9 = new Gtk.Label();
        this.label9.Name = "label9";
        this.label9.Xalign = 0F;
        this.label9.LabelProp = Mono.Unix.Catalog.GetString("WHERE");
        this.QueryTable.Add(this.label9);
        Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.QueryTable[this.label9]));
        w22.TopAttach = ((uint)(1));
        w22.BottomAttach = ((uint)(2));
        w22.XOptions = ((Gtk.AttachOptions)(4));
        w22.YOptions = ((Gtk.AttachOptions)(4));
        this.QueryBox.Add(this.QueryTable);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.QueryBox[this.QueryTable]));
        w23.Position = 0;
        // Container child QueryBox.Gtk.Box+BoxChild
        this.btnRunQuery = new Gtk.Button();
        this.btnRunQuery.CanFocus = true;
        this.btnRunQuery.Name = "btnRunQuery";
        this.btnRunQuery.UseUnderline = true;
        this.btnRunQuery.Label = Mono.Unix.Catalog.GetString("Run Query");
        this.QueryBox.Add(this.btnRunQuery);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.QueryBox[this.btnRunQuery]));
        w24.Position = 1;
        w24.Expand = false;
        w24.Fill = false;
        // Container child QueryBox.Gtk.Box+BoxChild
        this.btnColumns = new Gtk.Button();
        this.btnColumns.CanFocus = true;
        this.btnColumns.Name = "btnColumns";
        this.btnColumns.UseUnderline = true;
        this.btnColumns.Label = Mono.Unix.Catalog.GetString("Columns");
        this.QueryBox.Add(this.btnColumns);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.QueryBox[this.btnColumns]));
        w25.Position = 2;
        w25.Expand = false;
        w25.Fill = false;
        this.TableViewBox.Add(this.QueryBox);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.TableViewBox[this.QueryBox]));
        w26.Position = 0;
        w26.Expand = false;
        w26.Fill = false;
        // Container child TableViewBox.Gtk.Box+BoxChild
        this.TableView = new Gtk.ScrolledWindow();
        this.TableView.Name = "TableView";
        this.TableView.ShadowType = ((Gtk.ShadowType)(1));
        // Container child TableView.Gtk.Container+ContainerChild
        this.treeview1 = new Gtk.DataBindings.DataTreeView();
        this.treeview1.CanFocus = true;
        this.treeview1.Name = "treeview1";
        this.treeview1.HeadersClickable = true;
        this.treeview1.URIDragInSupport = false;
        this.treeview1.CursorPointsEveryType = false;
        this.treeview1.InheritedDataSource = false;
        this.treeview1.InheritedBoundaryDataSource = false;
        this.TableView.Add(this.treeview1);
        this.TableViewBox.Add(this.TableView);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.TableViewBox[this.TableView]));
        w28.Position = 1;
        // Container child TableViewBox.Gtk.Box+BoxChild
        this.datalabel3 = new Gtk.DataBindings.DataLabel();
        this.datalabel3.Name = "datalabel3";
        this.datalabel3.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
        this.datalabel3.InheritedDataSource = true;
        this.datalabel3.Mappings = "Query";
        this.datalabel3.InheritedBoundaryDataSource = false;
        this.TableViewBox.Add(this.datalabel3);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.TableViewBox[this.datalabel3]));
        w29.Position = 2;
        w29.Expand = false;
        w29.Fill = false;
        // Container child TableViewBox.Gtk.Box+BoxChild
        this.StatusBox = new Gtk.DataBindings.DataHBox();
        this.StatusBox.Name = "StatusBox";
        this.StatusBox.Spacing = 6;
        this.StatusBox.InheritedDataSource = true;
        this.StatusBox.InheritedBoundaryDataSource = false;
        // Container child StatusBox.Gtk.Box+BoxChild
        this.label11 = new Gtk.Label();
        this.label11.Name = "label11";
        this.label11.LabelProp = Mono.Unix.Catalog.GetString(" ");
        this.StatusBox.Add(this.label11);
        Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.StatusBox[this.label11]));
        w30.Position = 0;
        // Container child StatusBox.Gtk.Box+BoxChild
        this.datalabel4 = new Gtk.DataBindings.DataLabel();
        this.datalabel4.Name = "datalabel4";
        this.datalabel4.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
        this.datalabel4.Justify = ((Gtk.Justification)(1));
        this.datalabel4.InheritedDataSource = true;
        this.datalabel4.Mappings = "Status";
        this.datalabel4.InheritedBoundaryDataSource = false;
        this.StatusBox.Add(this.datalabel4);
        Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.StatusBox[this.datalabel4]));
        w31.Position = 2;
        w31.Expand = false;
        w31.Fill = false;
        this.TableViewBox.Add(this.StatusBox);
        Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.TableViewBox[this.StatusBox]));
        w32.Position = 3;
        w32.Expand = false;
        w32.Fill = false;
        this.WindowBox.Add(this.TableViewBox);
        Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.WindowBox[this.TableViewBox]));
        w33.Position = 1;
        this.Add(this.WindowBox);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 852;
        this.DefaultHeight = 381;
        this.TableViewBox.Hide();
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.TablesCB.Changed += new System.EventHandler(this.OnTablesCBChanged);
        this.DriversCB.Changed += new System.EventHandler(this.OnDriversCBChanged);
        this.DatasetsCB.Changed += new System.EventHandler(this.OnDatasetsCBChanged);
    }
}
