// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.DataBindings.DataVBox datavbox2;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.DataBindings.DataTreeView datatreeview1;
    
    private Gtk.DataBindings.DataComboBoxEntry datacomboboxentry1;
    
    private Gtk.DataBindings.DataComboBox datacombobox1;
    
    private Gtk.DataBindings.DataHBox datahbox1;
    
    private Gtk.Button button1;
    
    private Gtk.Button button2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.datavbox2 = new Gtk.DataBindings.DataVBox();
        this.datavbox2.Name = "datavbox2";
        this.datavbox2.Spacing = 6;
        this.datavbox2.InheritedDataSource = false;
        this.datavbox2.InheritedBoundaryDataSource = false;
        // Container child datavbox2.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.datatreeview1 = new Gtk.DataBindings.DataTreeView();
        this.datatreeview1.CanFocus = true;
        this.datatreeview1.Name = "datatreeview1";
        this.datatreeview1.CursorPointsEveryType = false;
        this.datatreeview1.InheritedDataSource = false;
        this.datatreeview1.InheritedBoundaryDataSource = false;
        this.datatreeview1.ColumnMappings = "{System.Data.DataRowView} ID[Id]; Title[Naslovcek]";
        this.GtkScrolledWindow.Add(this.datatreeview1);
        this.datavbox2.Add(this.GtkScrolledWindow);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.datavbox2[this.GtkScrolledWindow]));
        w2.Position = 0;
        // Container child datavbox2.Gtk.Box+BoxChild
        this.datacomboboxentry1 = new Gtk.DataBindings.DataComboBoxEntry();
        this.datacomboboxentry1.Name = "datacomboboxentry1";
        this.datacomboboxentry1.InheritedDataSource = false;
        this.datacomboboxentry1.ColumnMappings = "{System.Data.DataRowView} ID[Id]; Title[Naslovcek]";
        this.datacomboboxentry1.InheritedBoundaryDataSource = false;
        this.datacomboboxentry1.CursorPointsEveryType = false;
        this.datavbox2.Add(this.datacomboboxentry1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.datavbox2[this.datacomboboxentry1]));
        w3.Position = 1;
        w3.Expand = false;
        w3.Fill = false;
        // Container child datavbox2.Gtk.Box+BoxChild
        this.datacombobox1 = new Gtk.DataBindings.DataComboBox();
        this.datacombobox1.Name = "datacombobox1";
        this.datacombobox1.InheritedDataSource = false;
        this.datacombobox1.ColumnMappings = "{System.Data.DataRowView} ID[Id]; Title[Naslovcek]";
        this.datacombobox1.InheritedBoundaryDataSource = false;
        this.datacombobox1.CursorPointsEveryType = false;
        this.datavbox2.Add(this.datacombobox1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.datavbox2[this.datacombobox1]));
        w4.Position = 2;
        w4.Expand = false;
        w4.Fill = false;
        // Container child datavbox2.Gtk.Box+BoxChild
        this.datahbox1 = new Gtk.DataBindings.DataHBox();
        this.datahbox1.Name = "datahbox1";
        this.datahbox1.Spacing = 6;
        this.datahbox1.InheritedDataSource = false;
        this.datahbox1.InheritedBoundaryDataSource = false;
        // Container child datahbox1.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("Add new item");
        this.datahbox1.Add(this.button1);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.datahbox1[this.button1]));
        w5.Position = 0;
        w5.Expand = false;
        w5.Fill = false;
        // Container child datahbox1.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("Remove an item");
        this.datahbox1.Add(this.button2);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.datahbox1[this.button2]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        this.datavbox2.Add(this.datahbox1);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.datavbox2[this.datahbox1]));
        w7.Position = 3;
        w7.Expand = false;
        w7.Fill = false;
        this.Add(this.datavbox2);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.datatreeview1.CellDescription += new Gtk.DataBindings.CellDescriptionEvent(this.OnDatatreeview1CellDescription);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
    }
}
