
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.DataBindings.DataVBox datavbox2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.DataBindings.DataTreeView datatreeview1;
	
	private global::Gtk.DataBindings.DataComboBoxEntry datacomboboxentry1;
	
	private global::Gtk.DataBindings.DataComboBox datacombobox1;
	
	private global::Gtk.DataBindings.DataHBox datahbox1;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.datavbox2 = new global::Gtk.DataBindings.DataVBox ();
		this.datavbox2.Name = "datavbox2";
		this.datavbox2.Spacing = 6;
		this.datavbox2.InheritedDataSource = false;
		this.datavbox2.InheritedBoundaryDataSource = false;
		this.datavbox2.InheritedDataSource = false;
		this.datavbox2.InheritedBoundaryDataSource = false;
		// Container child datavbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.datatreeview1 = new global::Gtk.DataBindings.DataTreeView ();
		this.datatreeview1.CanFocus = true;
		this.datatreeview1.Name = "datatreeview1";
		this.datatreeview1.CursorPointsEveryType = false;
		this.datatreeview1.InheritedDataSource = false;
		this.datatreeview1.InheritedBoundaryDataSource = false;
		this.datatreeview1.InheritedDataSource = false;
		this.datatreeview1.InheritedBoundaryDataSource = false;
		this.datatreeview1.ColumnMappings = "{System.Data.DataRowView} ID[Id]; Title[Naslovcek]";
		this.GtkScrolledWindow.Add (this.datatreeview1);
		this.datavbox2.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.datavbox2 [this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child datavbox2.Gtk.Box+BoxChild
		this.datacomboboxentry1 = new global::Gtk.DataBindings.DataComboBoxEntry ();
		this.datacomboboxentry1.Name = "datacomboboxentry1";
		this.datacomboboxentry1.InheritedDataSource = false;
		this.datacomboboxentry1.ColumnMappings = "{System.Data.DataRowView} ID[Id]; Title[Naslovcek]";
		this.datacomboboxentry1.InheritedBoundaryDataSource = false;
		this.datacomboboxentry1.CursorPointsEveryType = false;
		this.datacomboboxentry1.InheritedDataSource = false;
		this.datacomboboxentry1.InheritedBoundaryDataSource = false;
		this.datavbox2.Add (this.datacomboboxentry1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.datavbox2 [this.datacomboboxentry1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child datavbox2.Gtk.Box+BoxChild
		this.datacombobox1 = new global::Gtk.DataBindings.DataComboBox ();
		this.datacombobox1.Name = "datacombobox1";
		this.datacombobox1.InheritedDataSource = false;
		this.datacombobox1.ColumnMappings = "{System.Data.DataRowView} ID[Id]; Title[Naslovcek]";
		this.datacombobox1.InheritedBoundaryDataSource = false;
		this.datacombobox1.CursorPointsEveryType = false;
		this.datacombobox1.InheritedDataSource = false;
		this.datacombobox1.InheritedBoundaryDataSource = false;
		this.datavbox2.Add (this.datacombobox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.datavbox2 [this.datacombobox1]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child datavbox2.Gtk.Box+BoxChild
		this.datahbox1 = new global::Gtk.DataBindings.DataHBox ();
		this.datahbox1.Name = "datahbox1";
		this.datahbox1.Spacing = 6;
		this.datahbox1.InheritedDataSource = false;
		this.datahbox1.InheritedBoundaryDataSource = false;
		this.datahbox1.InheritedDataSource = false;
		this.datahbox1.InheritedBoundaryDataSource = false;
		// Container child datahbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Add new item");
		this.datahbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.datahbox1 [this.button1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child datahbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Remove an item");
		this.datahbox1.Add (this.button2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.datahbox1 [this.button2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.datavbox2.Add (this.datahbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.datavbox2 [this.datahbox1]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		this.Add (this.datavbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.datatreeview1.CellDescription += new global::Gtk.DataBindings.CellDescriptionEvent (this.OnDatatreeview1CellDescription);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
