
// This file has been generated by the GUI designer. Do not modify.
namespace Gtk.DataBindings
{
	public partial class DataRadioGroup
	{
		private global::Gtk.VBox box;
		
		private global::Gtk.RadioButton RadioGroup;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtk.DataBindings.DataRadioGroup
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Gtk.DataBindings.DataRadioGroup";
			// Container child Gtk.DataBindings.DataRadioGroup.Gtk.Container+ContainerChild
			this.box = new global::Gtk.VBox ();
			this.box.Name = "box";
			this.box.Spacing = 6;
			// Container child box.Gtk.Box+BoxChild
			this.RadioGroup = new global::Gtk.RadioButton ("RadioGroup");
			this.RadioGroup.CanFocus = true;
			this.RadioGroup.Name = "RadioGroup";
			this.RadioGroup.Active = true;
			this.RadioGroup.DrawIndicator = true;
			this.RadioGroup.UseUnderline = true;
			this.RadioGroup.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.box.Add (this.RadioGroup);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.box [this.RadioGroup]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.box);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
