// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gtk.ExtraWidgets {
    
    
    public partial class DateCalculatorWindow {
        
        private Gtk.VBox vbox1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gtk.ExtraWidgets.DateCalculatorWindow
            this.Name = "Gtk.ExtraWidgets.DateCalculatorWindow";
            this.Title = "";
            this.TypeHint = ((Gdk.WindowTypeHint)(2));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            this.Decorated = false;
            // Container child Gtk.ExtraWidgets.DateCalculatorWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 63;
            this.Show();
            this.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnButtonPressEvent);
            this.KeyPressEvent += new Gtk.KeyPressEventHandler(this.OnKeyPressEvent);
            this.KeyReleaseEvent += new Gtk.KeyReleaseEventHandler(this.OnKeyReleaseEvent);
        }
    }
}
