
// This file has been generated by the GUI designer. Do not modify.
namespace Gtk.ExtraWidgets
{
	public partial class DateCalculatorWindow
	{
		private global::Gtk.VBox vbox1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gtk.ExtraWidgets.DateCalculatorWindow
			this.Name = "Gtk.ExtraWidgets.DateCalculatorWindow";
			this.Title = "";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			// Container child Gtk.ExtraWidgets.DateCalculatorWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 63;
			this.Show ();
			this.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnButtonPressEvent);
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnKeyReleaseEvent);
		}
	}
}
