// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Gtk.DataBindings {
    
    
    public partial class DataRadioGroup {
        
        private Gtk.VBox box;
        
        private Gtk.RadioButton RadioGroup;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Gtk.DataBindings.DataRadioGroup
            Stetic.BinContainer.Attach(this);
            this.Name = "Gtk.DataBindings.DataRadioGroup";
            // Container child Gtk.DataBindings.DataRadioGroup.Gtk.Container+ContainerChild
            this.box = new Gtk.VBox();
            this.box.Name = "box";
            this.box.Spacing = 6;
            // Container child box.Gtk.Box+BoxChild
            this.RadioGroup = new Gtk.RadioButton("RadioGroup");
            this.RadioGroup.CanFocus = true;
            this.RadioGroup.Name = "RadioGroup";
            this.RadioGroup.DrawIndicator = true;
            this.RadioGroup.UseUnderline = true;
            this.RadioGroup.Group = new GLib.SList(System.IntPtr.Zero);
            this.box.Add(this.RadioGroup);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.box[this.RadioGroup]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            this.Add(this.box);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
