
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action jkjhkAction;
	private global::Gtk.DataBindings.DataVBox datavbox1;
	private global::Gtk.DataBindings.DataSpinButton dataspinbutton2;
	private global::Gtk.DataBindings.DataEntry dataentry2;
	private global::Gtk.Label label1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.jkjhkAction = new global::Gtk.Action ("jkjhkAction", global::Mono.Unix.Catalog.GetString ("jkjhk"), null, null);
		this.jkjhkAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("jkjhk");
		w1.Add (this.jkjhkAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(8));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.datavbox1 = new global::Gtk.DataBindings.DataVBox ();
		this.datavbox1.Name = "datavbox1";
		this.datavbox1.Spacing = 6;
		this.datavbox1.InheritedDataSource = false;
		this.datavbox1.InheritedBoundaryDataSource = false;
		this.datavbox1.InheritedDataSource = false;
		this.datavbox1.InheritedBoundaryDataSource = false;
		// Container child datavbox1.Gtk.Box+BoxChild
		this.dataspinbutton2 = new global::Gtk.DataBindings.DataSpinButton (0, 100, 1);
		this.dataspinbutton2.CanFocus = true;
		this.dataspinbutton2.Name = "dataspinbutton2";
		this.dataspinbutton2.Adjustment.PageIncrement = 10;
		this.dataspinbutton2.ClimbRate = 1;
		this.dataspinbutton2.Numeric = true;
		this.dataspinbutton2.Value = 1;
		this.dataspinbutton2.InheritedDataSource = true;
		this.dataspinbutton2.Mappings = "IntValue";
		this.dataspinbutton2.InheritedBoundaryDataSource = false;
		this.dataspinbutton2.InheritedDataSource = true;
		this.dataspinbutton2.Mappings = "IntValue";
		this.dataspinbutton2.InheritedBoundaryDataSource = false;
		this.datavbox1.Add (this.dataspinbutton2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.datavbox1 [this.dataspinbutton2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child datavbox1.Gtk.Box+BoxChild
		this.dataentry2 = new global::Gtk.DataBindings.DataEntry ();
		this.dataentry2.CanFocus = true;
		this.dataentry2.Name = "dataentry2";
		this.dataentry2.IsEditable = true;
		this.dataentry2.InvisibleChar = '•';
		this.dataentry2.InheritedDataSource = true;
		this.dataentry2.Mappings = "StrValue";
		this.dataentry2.InheritedBoundaryDataSource = false;
		this.dataentry2.InheritedDataSource = true;
		this.dataentry2.Mappings = "StrValue";
		this.dataentry2.InheritedBoundaryDataSource = false;
		this.datavbox1.Add (this.dataentry2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.datavbox1 [this.dataentry2]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child datavbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("ConfigFile supports file monitoring, so in this example you can go to ~/.config/config_sample1 or config_sample1 in your Application Data on Windows and manually edit config.xml. Controls will auto update on save");
		this.label1.Wrap = true;
		this.datavbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.datavbox1 [this.label1]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.Add (this.datavbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1593;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.dataspinbutton2.LeaveNotifyEvent += new global::Gtk.LeaveNotifyEventHandler (this.OnDataspinbutton2LeaveNotifyEvent);
	}
}
