// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.Label label2;
    
    private Gtk.DataBindings.DataTable MainContainer;
    
    private Gtk.DataBindings.DataEntry dataentry1;
    
    private Gtk.DataBindings.DataEntry dataentry2;
    
    private Gtk.DataBindings.DataLabel datalabel1;
    
    private Gtk.Label label1;
    
    private Gtk.Label label3;
    
    private Gtk.Label label7;
    
    private Gtk.Label label4;
    
    private Gtk.DataBindings.DataTable MainContainer1;
    
    private Gtk.DataBindings.DataEntry dataentry3;
    
    private Gtk.DataBindings.DataEntry dataentry4;
    
    private Gtk.DataBindings.DataLabel datalabel2;
    
    private Gtk.Label label5;
    
    private Gtk.Label label6;
    
    private Gtk.Label label8;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("<b>Connected to first adaptor</b>");
        this.label2.UseMarkup = true;
        this.vbox1.Add(this.label2);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.label2]));
        w1.Position = 0;
        w1.Expand = false;
        w1.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.MainContainer = new Gtk.DataBindings.DataTable(((uint)(3)), ((uint)(2)), false);
        this.MainContainer.Name = "MainContainer";
        this.MainContainer.RowSpacing = ((uint)(6));
        this.MainContainer.ColumnSpacing = ((uint)(6));
        this.MainContainer.BorderWidth = ((uint)(6));
        this.MainContainer.InheritedDataSource = false;
        this.MainContainer.InheritedBoundaryDataSource = false;
        this.MainContainer.BoundaryMappings = "";
        // Container child MainContainer.Gtk.Table+TableChild
        this.dataentry1 = new Gtk.DataBindings.DataEntry();
        this.dataentry1.CanFocus = true;
        this.dataentry1.Name = "dataentry1";
        this.dataentry1.IsEditable = true;
        this.dataentry1.InvisibleChar = '•';
        this.dataentry1.InheritedDataSource = true;
        this.dataentry1.Mappings = "FirstName";
        this.dataentry1.InheritedBoundaryDataSource = false;
        this.dataentry1.BoundaryMappings = "";
        this.MainContainer.Add(this.dataentry1);
        Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.MainContainer[this.dataentry1]));
        w2.LeftAttach = ((uint)(1));
        w2.RightAttach = ((uint)(2));
        w2.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer.Gtk.Table+TableChild
        this.dataentry2 = new Gtk.DataBindings.DataEntry();
        this.dataentry2.CanFocus = true;
        this.dataentry2.Name = "dataentry2";
        this.dataentry2.IsEditable = true;
        this.dataentry2.InvisibleChar = '•';
        this.dataentry2.InheritedDataSource = true;
        this.dataentry2.Mappings = "LastName";
        this.dataentry2.InheritedBoundaryDataSource = false;
        this.dataentry2.BoundaryMappings = "";
        this.MainContainer.Add(this.dataentry2);
        Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.MainContainer[this.dataentry2]));
        w3.TopAttach = ((uint)(1));
        w3.BottomAttach = ((uint)(2));
        w3.LeftAttach = ((uint)(1));
        w3.RightAttach = ((uint)(2));
        w3.XOptions = ((Gtk.AttachOptions)(4));
        w3.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer.Gtk.Table+TableChild
        this.datalabel1 = new Gtk.DataBindings.DataLabel();
        this.datalabel1.Name = "datalabel1";
        this.datalabel1.InheritedDataSource = true;
        this.datalabel1.Mappings = "Name";
        this.datalabel1.InheritedBoundaryDataSource = false;
        this.datalabel1.BoundaryMappings = "";
        this.MainContainer.Add(this.datalabel1);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.MainContainer[this.datalabel1]));
        w4.TopAttach = ((uint)(2));
        w4.BottomAttach = ((uint)(3));
        w4.LeftAttach = ((uint)(1));
        w4.RightAttach = ((uint)(2));
        w4.XOptions = ((Gtk.AttachOptions)(4));
        w4.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer.Gtk.Table+TableChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.Xalign = 0F;
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Full name");
        this.MainContainer.Add(this.label1);
        Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.MainContainer[this.label1]));
        w5.TopAttach = ((uint)(2));
        w5.BottomAttach = ((uint)(3));
        w5.XOptions = ((Gtk.AttachOptions)(4));
        w5.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer.Gtk.Table+TableChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.Xalign = 0F;
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Last name");
        this.MainContainer.Add(this.label3);
        Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.MainContainer[this.label3]));
        w6.TopAttach = ((uint)(1));
        w6.BottomAttach = ((uint)(2));
        w6.XOptions = ((Gtk.AttachOptions)(4));
        w6.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer.Gtk.Table+TableChild
        this.label7 = new Gtk.Label();
        this.label7.Name = "label7";
        this.label7.Xalign = 0F;
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("First name");
        this.MainContainer.Add(this.label7);
        Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.MainContainer[this.label7]));
        w7.XOptions = ((Gtk.AttachOptions)(4));
        w7.YOptions = ((Gtk.AttachOptions)(4));
        this.vbox1.Add(this.MainContainer);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1[this.MainContainer]));
        w8.Position = 1;
        w8.Expand = false;
        w8.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("<b>Connected to second adaptor</b>");
        this.label4.UseMarkup = true;
        this.vbox1.Add(this.label4);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.label4]));
        w9.Position = 2;
        w9.Expand = false;
        w9.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.MainContainer1 = new Gtk.DataBindings.DataTable(((uint)(3)), ((uint)(2)), false);
        this.MainContainer1.Name = "MainContainer1";
        this.MainContainer1.RowSpacing = ((uint)(6));
        this.MainContainer1.ColumnSpacing = ((uint)(6));
        this.MainContainer1.BorderWidth = ((uint)(6));
        this.MainContainer1.InheritedDataSource = false;
        this.MainContainer1.InheritedBoundaryDataSource = false;
        this.MainContainer1.BoundaryMappings = "";
        // Container child MainContainer1.Gtk.Table+TableChild
        this.dataentry3 = new Gtk.DataBindings.DataEntry();
        this.dataentry3.CanFocus = true;
        this.dataentry3.Name = "dataentry3";
        this.dataentry3.IsEditable = true;
        this.dataentry3.InvisibleChar = '•';
        this.dataentry3.InheritedDataSource = true;
        this.dataentry3.Mappings = "LastName";
        this.dataentry3.InheritedBoundaryDataSource = false;
        this.dataentry3.BoundaryMappings = "";
        this.MainContainer1.Add(this.dataentry3);
        Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.MainContainer1[this.dataentry3]));
        w10.TopAttach = ((uint)(1));
        w10.BottomAttach = ((uint)(2));
        w10.LeftAttach = ((uint)(1));
        w10.RightAttach = ((uint)(2));
        w10.XOptions = ((Gtk.AttachOptions)(4));
        w10.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer1.Gtk.Table+TableChild
        this.dataentry4 = new Gtk.DataBindings.DataEntry();
        this.dataentry4.CanFocus = true;
        this.dataentry4.Name = "dataentry4";
        this.dataentry4.IsEditable = true;
        this.dataentry4.InvisibleChar = '•';
        this.dataentry4.InheritedDataSource = true;
        this.dataentry4.Mappings = "FirstName";
        this.dataentry4.InheritedBoundaryDataSource = false;
        this.dataentry4.BoundaryMappings = "";
        this.MainContainer1.Add(this.dataentry4);
        Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.MainContainer1[this.dataentry4]));
        w11.LeftAttach = ((uint)(1));
        w11.RightAttach = ((uint)(2));
        w11.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer1.Gtk.Table+TableChild
        this.datalabel2 = new Gtk.DataBindings.DataLabel();
        this.datalabel2.Name = "datalabel2";
        this.datalabel2.InheritedDataSource = true;
        this.datalabel2.Mappings = "Name";
        this.datalabel2.InheritedBoundaryDataSource = false;
        this.datalabel2.BoundaryMappings = "";
        this.MainContainer1.Add(this.datalabel2);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.MainContainer1[this.datalabel2]));
        w12.TopAttach = ((uint)(2));
        w12.BottomAttach = ((uint)(3));
        w12.LeftAttach = ((uint)(1));
        w12.RightAttach = ((uint)(2));
        w12.XOptions = ((Gtk.AttachOptions)(4));
        w12.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer1.Gtk.Table+TableChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.Xalign = 0F;
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("First name");
        this.MainContainer1.Add(this.label5);
        Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.MainContainer1[this.label5]));
        w13.XOptions = ((Gtk.AttachOptions)(4));
        w13.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer1.Gtk.Table+TableChild
        this.label6 = new Gtk.Label();
        this.label6.Name = "label6";
        this.label6.Xalign = 0F;
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("Full name");
        this.MainContainer1.Add(this.label6);
        Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.MainContainer1[this.label6]));
        w14.TopAttach = ((uint)(2));
        w14.BottomAttach = ((uint)(3));
        w14.XOptions = ((Gtk.AttachOptions)(4));
        w14.YOptions = ((Gtk.AttachOptions)(4));
        // Container child MainContainer1.Gtk.Table+TableChild
        this.label8 = new Gtk.Label();
        this.label8.Name = "label8";
        this.label8.Xalign = 0F;
        this.label8.LabelProp = Mono.Unix.Catalog.GetString("Last name");
        this.MainContainer1.Add(this.label8);
        Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.MainContainer1[this.label8]));
        w15.TopAttach = ((uint)(1));
        w15.BottomAttach = ((uint)(2));
        w15.XOptions = ((Gtk.AttachOptions)(4));
        w15.YOptions = ((Gtk.AttachOptions)(4));
        this.vbox1.Add(this.MainContainer1);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox1[this.MainContainer1]));
        w16.Position = 3;
        w16.Expand = false;
        w16.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 285;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
