// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action openAction;
    
    private Gtk.Action saveAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.DataBindings.DataTreeView addressview;
    
    private Gtk.VButtonBox vbuttonbox1;
    
    private Gtk.Button newaddress;
    
    private Gtk.Button newgroup;
    
    private Gtk.Button delete;
    
    private Gtk.Button properties;
    
    private Gtk.Button button163;
    
    private Gtk.DataBindings.DataVBox datavbox1;
    
    private Gtk.DataBindings.DataLabel datalabel1;
    
    private Gtk.DataBindings.DataLabel datalabel2;
    
    private Gtk.HButtonBox hbuttonbox1;
    
    private Gtk.Button close;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.openAction = new Gtk.Action("openAction", null, null, "gtk-open");
        w2.Add(this.openAction, null);
        this.saveAction = new Gtk.Action("saveAction", null, null, "gtk-save");
        w2.Add(this.saveAction, null);
        w1.InsertActionGroup(w2, 0);
        this.AddAccelGroup(w1.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 5;
        this.vbox1.BorderWidth = ((uint)(8));
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 8;
        // Container child hbox1.Gtk.Box+BoxChild
        this.addressview = new Gtk.DataBindings.DataTreeView();
        this.addressview.CanFocus = true;
        this.addressview.Name = "addressview";
        this.addressview.HeadersClickable = true;
        this.addressview.URIDragInSupport = false;
        this.addressview.CursorPointsEveryType = true;
        this.addressview.InheritedDataSource = false;
        this.addressview.Mappings = "";
        this.addressview.InheritedBoundaryDataSource = false;
        this.addressview.ColumnMappings = "{sample5.Address} FullName[Name]<>; Phone[Phone]; Email[Email]";
        this.hbox1.Add(this.addressview);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.addressview]));
        w3.Position = 0;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vbuttonbox1 = new Gtk.VButtonBox();
        this.vbuttonbox1.Name = "vbuttonbox1";
        this.vbuttonbox1.Spacing = 8;
        this.vbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
        // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.newaddress = new Gtk.Button();
        this.newaddress.CanFocus = true;
        this.newaddress.Name = "newaddress";
        this.newaddress.UseUnderline = true;
        // Container child newaddress.Gtk.Container+ContainerChild
        Gtk.Alignment w4 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w5 = new Gtk.HBox();
        w5.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w6 = new Gtk.Image();
        w6.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-new", Gtk.IconSize.Menu, 16);
        w5.Add(w6);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w8 = new Gtk.Label();
        w8.LabelProp = Mono.Unix.Catalog.GetString("Add address");
        w8.UseUnderline = true;
        w5.Add(w8);
        w4.Add(w5);
        this.newaddress.Add(w4);
        this.vbuttonbox1.Add(this.newaddress);
        Gtk.ButtonBox.ButtonBoxChild w12 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.newaddress]));
        w12.Expand = false;
        w12.Fill = false;
        // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.newgroup = new Gtk.Button();
        this.newgroup.CanFocus = true;
        this.newgroup.Name = "newgroup";
        this.newgroup.UseUnderline = true;
        // Container child newgroup.Gtk.Container+ContainerChild
        Gtk.Alignment w13 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w14 = new Gtk.HBox();
        w14.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w15 = new Gtk.Image();
        w15.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-dnd-multiple", Gtk.IconSize.Menu, 16);
        w14.Add(w15);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w17 = new Gtk.Label();
        w17.LabelProp = Mono.Unix.Catalog.GetString("Add group");
        w17.UseUnderline = true;
        w14.Add(w17);
        w13.Add(w14);
        this.newgroup.Add(w13);
        this.vbuttonbox1.Add(this.newgroup);
        Gtk.ButtonBox.ButtonBoxChild w21 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.newgroup]));
        w21.Position = 1;
        w21.Expand = false;
        w21.Fill = false;
        // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.delete = new Gtk.Button();
        this.delete.CanFocus = true;
        this.delete.Name = "delete";
        this.delete.UseUnderline = true;
        // Container child delete.Gtk.Container+ContainerChild
        Gtk.Alignment w22 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w23 = new Gtk.HBox();
        w23.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w24 = new Gtk.Image();
        w24.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_delete", Gtk.IconSize.Menu, 16);
        w23.Add(w24);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w26 = new Gtk.Label();
        w26.LabelProp = Mono.Unix.Catalog.GetString("Delete");
        w26.UseUnderline = true;
        w23.Add(w26);
        w22.Add(w23);
        this.delete.Add(w22);
        this.vbuttonbox1.Add(this.delete);
        Gtk.ButtonBox.ButtonBoxChild w30 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.delete]));
        w30.Position = 2;
        w30.Expand = false;
        w30.Fill = false;
        // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.properties = new Gtk.Button();
        this.properties.CanFocus = true;
        this.properties.Name = "properties";
        this.properties.UseStock = true;
        this.properties.UseUnderline = true;
        this.properties.Label = "gtk-properties";
        this.vbuttonbox1.Add(this.properties);
        Gtk.ButtonBox.ButtonBoxChild w31 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.properties]));
        w31.Position = 3;
        w31.Expand = false;
        w31.Fill = false;
        // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.button163 = new Gtk.Button();
        this.button163.CanFocus = true;
        this.button163.Name = "button163";
        this.button163.UseUnderline = true;
        this.button163.Label = Mono.Unix.Catalog.GetString("button163");
        this.vbuttonbox1.Add(this.button163);
        Gtk.ButtonBox.ButtonBoxChild w32 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button163]));
        w32.Position = 4;
        w32.Expand = false;
        w32.Fill = false;
        this.hbox1.Add(this.vbuttonbox1);
        Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox1]));
        w33.Position = 1;
        w33.Expand = false;
        w33.Fill = false;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w34.Position = 0;
        // Container child vbox1.Gtk.Box+BoxChild
        this.datavbox1 = new Gtk.DataBindings.DataVBox();
        this.datavbox1.Name = "datavbox1";
        this.datavbox1.Spacing = 6;
        this.datavbox1.InheritedDataSource = false;
        this.datavbox1.InheritedBoundaryDataSource = false;
        // Container child datavbox1.Gtk.Box+BoxChild
        this.datalabel1 = new Gtk.DataBindings.DataLabel();
        this.datalabel1.Name = "datalabel1";
        this.datalabel1.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
        this.datalabel1.InheritedDataSource = true;
        this.datalabel1.Mappings = "FullName";
        this.datalabel1.InheritedBoundaryDataSource = false;
        this.datavbox1.Add(this.datalabel1);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.datavbox1[this.datalabel1]));
        w35.Position = 0;
        w35.Expand = false;
        w35.Fill = false;
        // Container child datavbox1.Gtk.Box+BoxChild
        this.datalabel2 = new Gtk.DataBindings.DataLabel();
        this.datalabel2.Name = "datalabel2";
        this.datalabel2.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
        this.datalabel2.InheritedDataSource = true;
        this.datalabel2.Mappings = "Name";
        this.datalabel2.InheritedBoundaryDataSource = false;
        this.datavbox1.Add(this.datalabel2);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.datavbox1[this.datalabel2]));
        w36.Position = 1;
        w36.Expand = false;
        w36.Fill = false;
        this.vbox1.Add(this.datavbox1);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox1[this.datavbox1]));
        w37.Position = 1;
        w37.Expand = false;
        w37.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbuttonbox1 = new Gtk.HButtonBox();
        // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.close = new Gtk.Button();
        this.close.CanFocus = true;
        this.close.Name = "close";
        this.close.UseUnderline = true;
        // Container child close.Gtk.Container+ContainerChild
        Gtk.Alignment w38 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w39 = new Gtk.HBox();
        w39.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w40 = new Gtk.Image();
        w40.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-close", Gtk.IconSize.Menu, 16);
        w39.Add(w40);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w42 = new Gtk.Label();
        w42.LabelProp = Mono.Unix.Catalog.GetString("Close");
        w42.UseUnderline = true;
        w39.Add(w42);
        w38.Add(w39);
        this.close.Add(w38);
        this.hbuttonbox1.Add(this.close);
        Gtk.ButtonBox.ButtonBoxChild w46 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.close]));
        w46.Expand = false;
        w46.Fill = false;
        this.vbox1.Add(this.hbuttonbox1);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
        w47.Position = 2;
        w47.Expand = false;
        w47.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 720;
        this.DefaultHeight = 392;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.newaddress.Clicked += new System.EventHandler(this.OnNewaddressClicked);
        this.newgroup.Clicked += new System.EventHandler(this.OnNewgroupClicked);
        this.delete.Clicked += new System.EventHandler(this.OnDeleteClicked);
        this.properties.Clicked += new System.EventHandler(this.OnPropertiesClicked);
        this.button163.Clicked += new System.EventHandler(this.OnButton163Clicked);
        this.close.Clicked += new System.EventHandler(this.OnCloseClicked);
    }
}
