
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action openAction;
	private global::Gtk.Action saveAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.DataBindings.DataTreeView addressview;
	private global::Gtk.VButtonBox vbuttonbox1;
	private global::Gtk.Button newaddress;
	private global::Gtk.Button newgroup;
	private global::Gtk.Button delete;
	private global::Gtk.Button properties;
	private global::Gtk.Button button163;
	private global::Gtk.DataBindings.DataVBox datavbox1;
	private global::Gtk.DataBindings.DataLabel datalabel1;
	private global::Gtk.DataBindings.DataLabel datalabel2;
	private global::Gtk.HButtonBox hbuttonbox1;
	private global::Gtk.Button close;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 5;
		this.vbox1.BorderWidth = ((uint)(8));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 8;
		// Container child hbox1.Gtk.Box+BoxChild
		this.addressview = new global::Gtk.DataBindings.DataTreeView ();
		this.addressview.CanFocus = true;
		this.addressview.Name = "addressview";
		this.addressview.CursorPointsEveryType = true;
		this.addressview.InheritedDataSource = false;
		this.addressview.Mappings = "";
		this.addressview.InheritedBoundaryDataSource = false;
		this.addressview.InheritedDataSource = false;
		this.addressview.Mappings = "";
		this.addressview.InheritedBoundaryDataSource = false;
		this.addressview.ColumnMappings = "{sample5.Address} FullName[Name]<>; Phone[Phone]; Email[Email]";
		this.hbox1.Add (this.addressview);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.addressview]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox ();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.Spacing = 8;
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.newaddress = new global::Gtk.Button ();
		this.newaddress.CanFocus = true;
		this.newaddress.Name = "newaddress";
		this.newaddress.UseUnderline = true;
		// Container child newaddress.Gtk.Container+ContainerChild
		global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w4 = new global::Gtk.HBox ();
		w4.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w5 = new global::Gtk.Image ();
		w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.Menu);
		w4.Add (w5);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Add address");
		w7.UseUnderline = true;
		w4.Add (w7);
		w3.Add (w4);
		this.newaddress.Add (w3);
		this.vbuttonbox1.Add (this.newaddress);
		global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.newaddress]));
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.newgroup = new global::Gtk.Button ();
		this.newgroup.CanFocus = true;
		this.newgroup.Name = "newgroup";
		this.newgroup.UseUnderline = true;
		// Container child newgroup.Gtk.Container+ContainerChild
		global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w13 = new global::Gtk.HBox ();
		w13.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w14 = new global::Gtk.Image ();
		w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dnd-multiple", global::Gtk.IconSize.Menu);
		w13.Add (w14);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w16 = new global::Gtk.Label ();
		w16.LabelProp = global::Mono.Unix.Catalog.GetString ("Add group");
		w16.UseUnderline = true;
		w13.Add (w16);
		w12.Add (w13);
		this.newgroup.Add (w12);
		this.vbuttonbox1.Add (this.newgroup);
		global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.newgroup]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.delete = new global::Gtk.Button ();
		this.delete.CanFocus = true;
		this.delete.Name = "delete";
		this.delete.UseUnderline = true;
		// Container child delete.Gtk.Container+ContainerChild
		global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w22 = new global::Gtk.HBox ();
		w22.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w23 = new global::Gtk.Image ();
		w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_delete", global::Gtk.IconSize.Menu);
		w22.Add (w23);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w25 = new global::Gtk.Label ();
		w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete");
		w25.UseUnderline = true;
		w22.Add (w25);
		w21.Add (w22);
		this.delete.Add (w21);
		this.vbuttonbox1.Add (this.delete);
		global::Gtk.ButtonBox.ButtonBoxChild w29 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.delete]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.properties = new global::Gtk.Button ();
		this.properties.CanFocus = true;
		this.properties.Name = "properties";
		this.properties.UseStock = true;
		this.properties.UseUnderline = true;
		this.properties.Label = "gtk-properties";
		this.vbuttonbox1.Add (this.properties);
		global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.properties]));
		w30.Position = 3;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.button163 = new global::Gtk.Button ();
		this.button163.CanFocus = true;
		this.button163.Name = "button163";
		this.button163.UseUnderline = true;
		this.button163.Label = global::Mono.Unix.Catalog.GetString ("button163");
		this.vbuttonbox1.Add (this.button163);
		global::Gtk.ButtonBox.ButtonBoxChild w31 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.button163]));
		w31.Position = 4;
		w31.Expand = false;
		w31.Fill = false;
		this.hbox1.Add (this.vbuttonbox1);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbuttonbox1]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w33.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.datavbox1 = new global::Gtk.DataBindings.DataVBox ();
		this.datavbox1.Name = "datavbox1";
		this.datavbox1.Spacing = 6;
		this.datavbox1.InheritedDataSource = false;
		this.datavbox1.InheritedBoundaryDataSource = false;
		this.datavbox1.InheritedDataSource = false;
		this.datavbox1.InheritedBoundaryDataSource = false;
		// Container child datavbox1.Gtk.Box+BoxChild
		this.datalabel1 = new global::Gtk.DataBindings.DataLabel ();
		this.datalabel1.Name = "datalabel1";
		this.datalabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("datalabel1");
		this.datalabel1.InheritedDataSource = true;
		this.datalabel1.Mappings = "FullName";
		this.datalabel1.InheritedBoundaryDataSource = false;
		this.datalabel1.Important = false;
		this.datalabel1.InheritedDataSource = true;
		this.datalabel1.Mappings = "FullName";
		this.datalabel1.InheritedBoundaryDataSource = false;
		this.datavbox1.Add (this.datalabel1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.datavbox1 [this.datalabel1]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child datavbox1.Gtk.Box+BoxChild
		this.datalabel2 = new global::Gtk.DataBindings.DataLabel ();
		this.datalabel2.Name = "datalabel2";
		this.datalabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("datalabel1");
		this.datalabel2.InheritedDataSource = true;
		this.datalabel2.Mappings = "Name";
		this.datalabel2.InheritedBoundaryDataSource = false;
		this.datalabel2.Important = false;
		this.datalabel2.InheritedDataSource = true;
		this.datalabel2.Mappings = "Name";
		this.datalabel2.InheritedBoundaryDataSource = false;
		this.datavbox1.Add (this.datalabel2);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.datavbox1 [this.datalabel2]));
		w35.Position = 1;
		w35.Expand = false;
		w35.Fill = false;
		this.vbox1.Add (this.datavbox1);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.datavbox1]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.close = new global::Gtk.Button ();
		this.close.CanFocus = true;
		this.close.Name = "close";
		this.close.UseUnderline = true;
		// Container child close.Gtk.Container+ContainerChild
		global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w38 = new global::Gtk.HBox ();
		w38.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w39 = new global::Gtk.Image ();
		w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
		w38.Add (w39);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w41 = new global::Gtk.Label ();
		w41.LabelProp = global::Mono.Unix.Catalog.GetString ("Close");
		w41.UseUnderline = true;
		w38.Add (w41);
		w37.Add (w38);
		this.close.Add (w37);
		this.hbuttonbox1.Add (this.close);
		global::Gtk.ButtonBox.ButtonBoxChild w45 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.close]));
		w45.Expand = false;
		w45.Fill = false;
		this.vbox1.Add (this.hbuttonbox1);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
		w46.Position = 2;
		w46.Expand = false;
		w46.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 720;
		this.DefaultHeight = 392;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.newaddress.Clicked += new global::System.EventHandler (this.OnNewaddressClicked);
		this.newgroup.Clicked += new global::System.EventHandler (this.OnNewgroupClicked);
		this.delete.Clicked += new global::System.EventHandler (this.OnDeleteClicked);
		this.properties.Clicked += new global::System.EventHandler (this.OnPropertiesClicked);
		this.button163.Clicked += new global::System.EventHandler (this.OnButton163Clicked);
		this.close.Clicked += new global::System.EventHandler (this.OnCloseClicked);
	}
}
