
// This file has been generated by the GUI designer. Do not modify.
namespace sample5
{
	public partial class NewAddress
	{
		private global::Gtk.DataBindings.DataTable datatable1;
		private global::Gtk.DataBindings.DataEntry dataentry2;
		private global::Gtk.DataBindings.DataEntry dataentry3;
		private global::Gtk.DataBindings.DataEntry dataentry4;
		private global::Gtk.DataBindings.DataEntry dataentry5;
		private global::Gtk.DataBindings.DataEntry dataentry6;
		private global::Gtk.DataBindings.DataEntry dataentry7;
		private global::Gtk.DataBindings.DataLabel datalabel1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;
		private global::Gtk.Label label8;
		private global::Gtk.Button button90;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget sample5.NewAddress
			this.Events = ((global::Gdk.EventMask)(256));
			this.Name = "sample5.NewAddress";
			this.Title = global::Mono.Unix.Catalog.GetString ("NewAddress");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(8));
			this.AllowShrink = true;
			// Internal child sample5.NewAddress.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Events = ((global::Gdk.EventMask)(256));
			w1.Name = "dialog_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog_VBox.Gtk.Box+BoxChild
			this.datatable1 = new global::Gtk.DataBindings.DataTable (((uint)(8)), ((uint)(2)), false);
			this.datatable1.Name = "datatable1";
			this.datatable1.RowSpacing = ((uint)(4));
			this.datatable1.ColumnSpacing = ((uint)(8));
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			this.datatable1.InheritedDataSource = false;
			this.datatable1.InheritedBoundaryDataSource = false;
			// Container child datatable1.Gtk.Table+TableChild
			this.dataentry2 = new global::Gtk.DataBindings.DataEntry ();
			this.dataentry2.CanFocus = true;
			this.dataentry2.Name = "dataentry2";
			this.dataentry2.IsEditable = true;
			this.dataentry2.InvisibleChar = '•';
			this.dataentry2.InheritedDataSource = true;
			this.dataentry2.Mappings = "Name";
			this.dataentry2.InheritedBoundaryDataSource = false;
			this.dataentry2.InheritedDataSource = true;
			this.dataentry2.Mappings = "Name";
			this.dataentry2.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.dataentry2);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry2]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.dataentry3 = new global::Gtk.DataBindings.DataEntry ();
			this.dataentry3.CanFocus = true;
			this.dataentry3.Name = "dataentry3";
			this.dataentry3.IsEditable = true;
			this.dataentry3.InvisibleChar = '•';
			this.dataentry3.InheritedDataSource = true;
			this.dataentry3.Mappings = "MiddleName";
			this.dataentry3.InheritedBoundaryDataSource = false;
			this.dataentry3.InheritedDataSource = true;
			this.dataentry3.Mappings = "MiddleName";
			this.dataentry3.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.dataentry3);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry3]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.dataentry4 = new global::Gtk.DataBindings.DataEntry ();
			this.dataentry4.CanFocus = true;
			this.dataentry4.Name = "dataentry4";
			this.dataentry4.IsEditable = true;
			this.dataentry4.InvisibleChar = '•';
			this.dataentry4.InheritedDataSource = true;
			this.dataentry4.Mappings = "LastName";
			this.dataentry4.InheritedBoundaryDataSource = false;
			this.dataentry4.InheritedDataSource = true;
			this.dataentry4.Mappings = "LastName";
			this.dataentry4.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.dataentry4);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry4]));
			w4.TopAttach = ((uint)(3));
			w4.BottomAttach = ((uint)(4));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.dataentry5 = new global::Gtk.DataBindings.DataEntry ();
			this.dataentry5.CanFocus = true;
			this.dataentry5.Name = "dataentry5";
			this.dataentry5.IsEditable = true;
			this.dataentry5.InvisibleChar = '•';
			this.dataentry5.InheritedDataSource = true;
			this.dataentry5.Mappings = "Phone";
			this.dataentry5.InheritedBoundaryDataSource = false;
			this.dataentry5.InheritedDataSource = true;
			this.dataentry5.Mappings = "Phone";
			this.dataentry5.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.dataentry5);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry5]));
			w5.TopAttach = ((uint)(5));
			w5.BottomAttach = ((uint)(6));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.dataentry6 = new global::Gtk.DataBindings.DataEntry ();
			this.dataentry6.CanFocus = true;
			this.dataentry6.Name = "dataentry6";
			this.dataentry6.IsEditable = true;
			this.dataentry6.InvisibleChar = '•';
			this.dataentry6.InheritedDataSource = true;
			this.dataentry6.Mappings = "WebPage";
			this.dataentry6.InheritedBoundaryDataSource = false;
			this.dataentry6.InheritedDataSource = true;
			this.dataentry6.Mappings = "WebPage";
			this.dataentry6.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.dataentry6);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry6]));
			w6.TopAttach = ((uint)(6));
			w6.BottomAttach = ((uint)(7));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.dataentry7 = new global::Gtk.DataBindings.DataEntry ();
			this.dataentry7.CanFocus = true;
			this.dataentry7.Name = "dataentry7";
			this.dataentry7.IsEditable = true;
			this.dataentry7.InvisibleChar = '•';
			this.dataentry7.InheritedDataSource = true;
			this.dataentry7.Mappings = "Email";
			this.dataentry7.InheritedBoundaryDataSource = false;
			this.dataentry7.InheritedDataSource = true;
			this.dataentry7.Mappings = "Email";
			this.dataentry7.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.dataentry7);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry7]));
			w7.TopAttach = ((uint)(7));
			w7.BottomAttach = ((uint)(8));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.datalabel1 = new global::Gtk.DataBindings.DataLabel ();
			this.datalabel1.Name = "datalabel1";
			this.datalabel1.Xalign = 0F;
			this.datalabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("datalabel1");
			this.datalabel1.InheritedDataSource = true;
			this.datalabel1.Mappings = "FullName";
			this.datalabel1.InheritedBoundaryDataSource = false;
			this.datalabel1.Important = false;
			this.datalabel1.InheritedDataSource = true;
			this.datalabel1.Mappings = "FullName";
			this.datalabel1.InheritedBoundaryDataSource = false;
			this.datatable1.Add (this.datalabel1);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.datalabel1]));
			w8.TopAttach = ((uint)(4));
			w8.BottomAttach = ((uint)(5));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("First Name");
			this.datatable1.Add (this.label2);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label2]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Middle Name");
			this.datatable1.Add (this.label3);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label3]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Last Name");
			this.datatable1.Add (this.label4);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label4]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Full Name");
			this.datatable1.Add (this.label5);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label5]));
			w12.TopAttach = ((uint)(4));
			w12.BottomAttach = ((uint)(5));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Phone");
			this.datatable1.Add (this.label6);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label6]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Email");
			this.datatable1.Add (this.label7);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label7]));
			w14.TopAttach = ((uint)(7));
			w14.BottomAttach = ((uint)(8));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child datatable1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Webpage");
			this.datatable1.Add (this.label8);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label8]));
			w15.TopAttach = ((uint)(6));
			w15.BottomAttach = ((uint)(7));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.datatable1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(w1 [this.datatable1]));
			w16.Position = 0;
			// Internal child sample5.NewAddress.ActionArea
			global::Gtk.HButtonBox w17 = this.ActionArea;
			w17.Events = ((global::Gdk.EventMask)(256));
			w17.Name = "sample5.NewAddress_ActionArea";
			w17.Spacing = 6;
			w17.BorderWidth = ((uint)(5));
			w17.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child sample5.NewAddress_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button90 = new global::Gtk.Button ();
			this.button90.CanDefault = true;
			this.button90.CanFocus = true;
			this.button90.Name = "button90";
			this.button90.UseStock = true;
			this.button90.UseUnderline = true;
			this.button90.Label = "gtk-ok";
			this.AddActionWidget (this.button90, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w17 [this.button90]));
			w18.Expand = false;
			w18.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 323;
			this.Show ();
			this.button90.Clicked += new global::System.EventHandler (this.OnButton90Clicked);
		}
	}
}
