// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sample5 {
    
    
    public partial class NewAddress {
        
        private Gtk.DataBindings.DataTable datatable1;
        
        private Gtk.DataBindings.DataEntry dataentry2;
        
        private Gtk.DataBindings.DataEntry dataentry3;
        
        private Gtk.DataBindings.DataEntry dataentry4;
        
        private Gtk.DataBindings.DataEntry dataentry5;
        
        private Gtk.DataBindings.DataEntry dataentry6;
        
        private Gtk.DataBindings.DataEntry dataentry7;
        
        private Gtk.DataBindings.DataLabel datalabel1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private Gtk.Button button90;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sample5.NewAddress
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "sample5.NewAddress";
            this.Title = Mono.Unix.Catalog.GetString("NewAddress");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.BorderWidth = ((uint)(8));
            this.AllowShrink = true;
            this.HasSeparator = false;
            // Internal child sample5.NewAddress.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.datatable1 = new Gtk.DataBindings.DataTable(((uint)(8)), ((uint)(2)), false);
            this.datatable1.Name = "datatable1";
            this.datatable1.RowSpacing = ((uint)(4));
            this.datatable1.ColumnSpacing = ((uint)(8));
            this.datatable1.InheritedDataSource = false;
            this.datatable1.InheritedBoundaryDataSource = false;
            // Container child datatable1.Gtk.Table+TableChild
            this.dataentry2 = new Gtk.DataBindings.DataEntry();
            this.dataentry2.CanFocus = true;
            this.dataentry2.Name = "dataentry2";
            this.dataentry2.IsEditable = true;
            this.dataentry2.InvisibleChar = '•';
            this.dataentry2.InheritedDataSource = true;
            this.dataentry2.Mappings = "Name";
            this.dataentry2.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.dataentry2);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry2]));
            w2.TopAttach = ((uint)(1));
            w2.BottomAttach = ((uint)(2));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.dataentry3 = new Gtk.DataBindings.DataEntry();
            this.dataentry3.CanFocus = true;
            this.dataentry3.Name = "dataentry3";
            this.dataentry3.IsEditable = true;
            this.dataentry3.InvisibleChar = '•';
            this.dataentry3.InheritedDataSource = true;
            this.dataentry3.Mappings = "MiddleName";
            this.dataentry3.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.dataentry3);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry3]));
            w3.TopAttach = ((uint)(2));
            w3.BottomAttach = ((uint)(3));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.dataentry4 = new Gtk.DataBindings.DataEntry();
            this.dataentry4.CanFocus = true;
            this.dataentry4.Name = "dataentry4";
            this.dataentry4.IsEditable = true;
            this.dataentry4.InvisibleChar = '•';
            this.dataentry4.InheritedDataSource = true;
            this.dataentry4.Mappings = "LastName";
            this.dataentry4.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.dataentry4);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry4]));
            w4.TopAttach = ((uint)(3));
            w4.BottomAttach = ((uint)(4));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.dataentry5 = new Gtk.DataBindings.DataEntry();
            this.dataentry5.CanFocus = true;
            this.dataentry5.Name = "dataentry5";
            this.dataentry5.IsEditable = true;
            this.dataentry5.InvisibleChar = '•';
            this.dataentry5.InheritedDataSource = true;
            this.dataentry5.Mappings = "Phone";
            this.dataentry5.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.dataentry5);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry5]));
            w5.TopAttach = ((uint)(5));
            w5.BottomAttach = ((uint)(6));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.dataentry6 = new Gtk.DataBindings.DataEntry();
            this.dataentry6.CanFocus = true;
            this.dataentry6.Name = "dataentry6";
            this.dataentry6.IsEditable = true;
            this.dataentry6.InvisibleChar = '•';
            this.dataentry6.InheritedDataSource = true;
            this.dataentry6.Mappings = "WebPage";
            this.dataentry6.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.dataentry6);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry6]));
            w6.TopAttach = ((uint)(6));
            w6.BottomAttach = ((uint)(7));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.dataentry7 = new Gtk.DataBindings.DataEntry();
            this.dataentry7.CanFocus = true;
            this.dataentry7.Name = "dataentry7";
            this.dataentry7.IsEditable = true;
            this.dataentry7.InvisibleChar = '•';
            this.dataentry7.InheritedDataSource = true;
            this.dataentry7.Mappings = "Email";
            this.dataentry7.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.dataentry7);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry7]));
            w7.TopAttach = ((uint)(7));
            w7.BottomAttach = ((uint)(8));
            w7.LeftAttach = ((uint)(1));
            w7.RightAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.datalabel1 = new Gtk.DataBindings.DataLabel();
            this.datalabel1.Name = "datalabel1";
            this.datalabel1.Xalign = 0F;
            this.datalabel1.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
            this.datalabel1.InheritedDataSource = true;
            this.datalabel1.Mappings = "FullName";
            this.datalabel1.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.datalabel1);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.datatable1[this.datalabel1]));
            w8.TopAttach = ((uint)(4));
            w8.BottomAttach = ((uint)(5));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("First Name");
            this.datatable1.Add(this.label2);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.datatable1[this.label2]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Middle Name");
            this.datatable1.Add(this.label3);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.datatable1[this.label3]));
            w10.TopAttach = ((uint)(2));
            w10.BottomAttach = ((uint)(3));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Last Name");
            this.datatable1.Add(this.label4);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.datatable1[this.label4]));
            w11.TopAttach = ((uint)(3));
            w11.BottomAttach = ((uint)(4));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Full Name");
            this.datatable1.Add(this.label5);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.datatable1[this.label5]));
            w12.TopAttach = ((uint)(4));
            w12.BottomAttach = ((uint)(5));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Phone");
            this.datatable1.Add(this.label6);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.datatable1[this.label6]));
            w13.TopAttach = ((uint)(5));
            w13.BottomAttach = ((uint)(6));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Email");
            this.datatable1.Add(this.label7);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.datatable1[this.label7]));
            w14.TopAttach = ((uint)(7));
            w14.BottomAttach = ((uint)(8));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 0F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Webpage");
            this.datatable1.Add(this.label8);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.datatable1[this.label8]));
            w15.TopAttach = ((uint)(6));
            w15.BottomAttach = ((uint)(7));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            w1.Add(this.datatable1);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(w1[this.datatable1]));
            w16.Position = 0;
            // Internal child sample5.NewAddress.ActionArea
            Gtk.HButtonBox w17 = this.ActionArea;
            w17.Events = ((Gdk.EventMask)(256));
            w17.Name = "sample5.NewAddress_ActionArea";
            w17.Spacing = 6;
            w17.BorderWidth = ((uint)(5));
            w17.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child sample5.NewAddress_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button90 = new Gtk.Button();
            this.button90.CanDefault = true;
            this.button90.CanFocus = true;
            this.button90.Name = "button90";
            this.button90.UseStock = true;
            this.button90.UseUnderline = true;
            this.button90.Label = "gtk-ok";
            this.AddActionWidget(this.button90, -5);
            Gtk.ButtonBox.ButtonBoxChild w18 = ((Gtk.ButtonBox.ButtonBoxChild)(w17[this.button90]));
            w18.Expand = false;
            w18.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 323;
            this.Show();
            this.button90.Clicked += new System.EventHandler(this.OnButton90Clicked);
        }
    }
}
