// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sample5 {
    
    
    public partial class NewGroup {
        
        private Gtk.HBox hbox2;
        
        private Gtk.Label label1;
        
        private Gtk.DataBindings.DataEntry dataentry1;
        
        private Gtk.Button button56;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sample5.NewGroup
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "sample5.NewGroup";
            this.Title = Mono.Unix.Catalog.GetString("Add Group");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.AllowShrink = true;
            this.HasSeparator = false;
            // Internal child sample5.NewGroup.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 8;
            // Container child hbox2.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Group name");
            this.hbox2.Add(this.label1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox2[this.label1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.dataentry1 = new Gtk.DataBindings.DataEntry();
            this.dataentry1.CanFocus = true;
            this.dataentry1.Name = "dataentry1";
            this.dataentry1.IsEditable = true;
            this.dataentry1.InvisibleChar = '•';
            this.dataentry1.InheritedDataSource = false;
            this.dataentry1.Mappings = "FullName";
            this.dataentry1.InheritedBoundaryDataSource = false;
            this.hbox2.Add(this.dataentry1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox2[this.dataentry1]));
            w3.Position = 1;
            w1.Add(this.hbox2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(w1[this.hbox2]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Internal child sample5.NewGroup.ActionArea
            Gtk.HButtonBox w5 = this.ActionArea;
            w5.Events = ((Gdk.EventMask)(256));
            w5.Name = "sample5.NewGroup_ActionArea";
            w5.Spacing = 6;
            w5.BorderWidth = ((uint)(5));
            w5.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child sample5.NewGroup_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button56 = new Gtk.Button();
            this.button56.CanDefault = true;
            this.button56.CanFocus = true;
            this.button56.Name = "button56";
            this.button56.UseStock = true;
            this.button56.UseUnderline = true;
            this.button56.Label = "gtk-ok";
            this.AddActionWidget(this.button56, -5);
            Gtk.ButtonBox.ButtonBoxChild w6 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.button56]));
            w6.Expand = false;
            w6.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 117;
            this.Show();
            this.button56.Clicked += new System.EventHandler(this.OnButton56Clicked);
        }
    }
}
