
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.DataBindings.DataVBox MainBox;
	private global::Gtk.DataBindings.DataTable datatable1;
	private global::Gtk.DataBindings.DataEntry dataentry1;
	private global::Gtk.DataBindings.DataEntry dataentry2;
	private global::Gtk.DataBindings.DataSpinButton dataspinbutton1;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label3;
	private global::Gtk.DataBindings.DataTable datatable2;
	private global::Gtk.DataBindings.DataLabel datalabel1;
	private global::Gtk.DataBindings.DataLabel datalabel2;
	private global::Gtk.DataBindings.DataLabel datalabel3;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Label label6;
	private global::Gtk.DataBindings.DataHBox datahbox1;
	private global::Gtk.Button button1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainBox = new global::Gtk.DataBindings.DataVBox ();
		this.MainBox.Name = "MainBox";
		this.MainBox.Spacing = 6;
		this.MainBox.BorderWidth = ((uint)(8));
		this.MainBox.InheritedDataSource = false;
		this.MainBox.InheritedBoundaryDataSource = false;
		this.MainBox.InheritedDataSource = false;
		this.MainBox.InheritedBoundaryDataSource = false;
		// Container child MainBox.Gtk.Box+BoxChild
		this.datatable1 = new global::Gtk.DataBindings.DataTable (((uint)(3)), ((uint)(2)), false);
		this.datatable1.Name = "datatable1";
		this.datatable1.RowSpacing = ((uint)(6));
		this.datatable1.ColumnSpacing = ((uint)(6));
		this.datatable1.InheritedDataSource = true;
		this.datatable1.InheritedBoundaryDataSource = false;
		this.datatable1.InheritedDataSource = true;
		this.datatable1.InheritedBoundaryDataSource = false;
		// Container child datatable1.Gtk.Table+TableChild
		this.dataentry1 = new global::Gtk.DataBindings.DataEntry ();
		this.dataentry1.CanFocus = true;
		this.dataentry1.Name = "dataentry1";
		this.dataentry1.IsEditable = true;
		this.dataentry1.InvisibleChar = '•';
		this.dataentry1.InheritedDataSource = true;
		this.dataentry1.Mappings = "Name";
		this.dataentry1.InheritedBoundaryDataSource = false;
		this.dataentry1.InheritedDataSource = true;
		this.dataentry1.Mappings = "Name";
		this.dataentry1.InheritedBoundaryDataSource = false;
		this.datatable1.Add (this.dataentry1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry1]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.dataentry2 = new global::Gtk.DataBindings.DataEntry ();
		this.dataentry2.CanFocus = true;
		this.dataentry2.Name = "dataentry2";
		this.dataentry2.IsEditable = true;
		this.dataentry2.InvisibleChar = '•';
		this.dataentry2.InheritedDataSource = true;
		this.dataentry2.Mappings = "LastName";
		this.dataentry2.InheritedBoundaryDataSource = false;
		this.dataentry2.InheritedDataSource = true;
		this.dataentry2.Mappings = "LastName";
		this.dataentry2.InheritedBoundaryDataSource = false;
		this.datatable1.Add (this.dataentry2);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry2]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.dataspinbutton1 = new global::Gtk.DataBindings.DataSpinButton (0, 100, 1);
		this.dataspinbutton1.CanFocus = true;
		this.dataspinbutton1.Name = "dataspinbutton1";
		this.dataspinbutton1.Adjustment.PageIncrement = 10;
		this.dataspinbutton1.ClimbRate = 1;
		this.dataspinbutton1.Numeric = true;
		this.dataspinbutton1.InheritedDataSource = true;
		this.dataspinbutton1.Mappings = "Age";
		this.dataspinbutton1.InheritedBoundaryDataSource = false;
		this.dataspinbutton1.InheritedDataSource = true;
		this.dataspinbutton1.Mappings = "Age";
		this.dataspinbutton1.InheritedBoundaryDataSource = false;
		this.datatable1.Add (this.dataspinbutton1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataspinbutton1]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
		this.datatable1.Add (this.label1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label1]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("LastName");
		this.datatable1.Add (this.label2);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label2]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Age");
		this.datatable1.Add (this.label3);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label3]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.MainBox.Add (this.datatable1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.MainBox [this.datatable1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child MainBox.Gtk.Box+BoxChild
		this.datatable2 = new global::Gtk.DataBindings.DataTable (((uint)(3)), ((uint)(2)), false);
		this.datatable2.Name = "datatable2";
		this.datatable2.RowSpacing = ((uint)(6));
		this.datatable2.ColumnSpacing = ((uint)(6));
		this.datatable2.InheritedDataSource = true;
		this.datatable2.InheritedBoundaryDataSource = false;
		this.datatable2.InheritedDataSource = true;
		this.datatable2.InheritedBoundaryDataSource = false;
		// Container child datatable2.Gtk.Table+TableChild
		this.datalabel1 = new global::Gtk.DataBindings.DataLabel ();
		this.datalabel1.Name = "datalabel1";
		this.datalabel1.Xalign = 0F;
		this.datalabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("datalabel1");
		this.datalabel1.InheritedDataSource = true;
		this.datalabel1.Mappings = "Name";
		this.datalabel1.InheritedBoundaryDataSource = false;
		this.datalabel1.Important = false;
		this.datalabel1.InheritedDataSource = true;
		this.datalabel1.Mappings = "Name";
		this.datalabel1.InheritedBoundaryDataSource = false;
		this.datatable2.Add (this.datalabel1);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.datalabel1]));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable2.Gtk.Table+TableChild
		this.datalabel2 = new global::Gtk.DataBindings.DataLabel ();
		this.datalabel2.Name = "datalabel2";
		this.datalabel2.Xalign = 0F;
		this.datalabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("datalabel2");
		this.datalabel2.InheritedDataSource = true;
		this.datalabel2.Mappings = "LastName";
		this.datalabel2.InheritedBoundaryDataSource = false;
		this.datalabel2.Important = false;
		this.datalabel2.InheritedDataSource = true;
		this.datalabel2.Mappings = "LastName";
		this.datalabel2.InheritedBoundaryDataSource = false;
		this.datatable2.Add (this.datalabel2);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.datalabel2]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable2.Gtk.Table+TableChild
		this.datalabel3 = new global::Gtk.DataBindings.DataLabel ();
		this.datalabel3.Name = "datalabel3";
		this.datalabel3.Xalign = 0F;
		this.datalabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("datalabel3");
		this.datalabel3.InheritedDataSource = true;
		this.datalabel3.Mappings = "Age";
		this.datalabel3.InheritedBoundaryDataSource = false;
		this.datalabel3.Important = false;
		this.datalabel3.InheritedDataSource = true;
		this.datalabel3.Mappings = "Age";
		this.datalabel3.InheritedBoundaryDataSource = false;
		this.datatable2.Add (this.datalabel3);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.datalabel3]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Name in object");
		this.datatable2.Add (this.label4);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label4]));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("LastName in object");
		this.datatable2.Add (this.label5);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label5]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable2.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Age in object");
		this.datatable2.Add (this.label6);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.datatable2 [this.label6]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		this.MainBox.Add (this.datatable2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.MainBox [this.datatable2]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child MainBox.Gtk.Box+BoxChild
		this.datahbox1 = new global::Gtk.DataBindings.DataHBox ();
		this.datahbox1.Name = "datahbox1";
		this.datahbox1.Spacing = 6;
		this.datahbox1.InheritedDataSource = false;
		this.datahbox1.InheritedBoundaryDataSource = false;
		this.datahbox1.InheritedDataSource = false;
		this.datahbox1.InheritedBoundaryDataSource = false;
		// Container child datahbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("button1");
		this.datahbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.datahbox1 [this.button1]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.MainBox.Add (this.datahbox1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.MainBox [this.datahbox1]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		this.Add (this.MainBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
