
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.DataBindings.DataTable datatable1;
	private global::Gtk.DataBindings.DataEntry dataentry1;
	private global::Gtk.DataBindings.DataEntry dataentry2;
	private global::Gtk.DataBindings.DataExpander dataexpander1;
	private global::Gtk.DataBindings.DataCalendar datacalendar1;
	private global::Gtk.Label GtkLabel4;
	private global::Gtk.DataBindings.DataLabel datalabel1;
	private global::Gtk.Label label1;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Label label6;
	private global::Gtk.HBox hbox1;
	private global::Gtk.CheckButton checkbutton1;
	private global::Gtk.Button button1;
	private global::Gtk.Button button2;
	private global::Gtk.Button button3;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 4;
		this.vbox1.BorderWidth = ((uint)(4));
		// Container child vbox1.Gtk.Box+BoxChild
		this.datatable1 = new global::Gtk.DataBindings.DataTable (((uint)(4)), ((uint)(2)), false);
		this.datatable1.Name = "datatable1";
		this.datatable1.RowSpacing = ((uint)(4));
		this.datatable1.ColumnSpacing = ((uint)(8));
		this.datatable1.BorderWidth = ((uint)(4));
		this.datatable1.InheritedDataSource = false;
		this.datatable1.InheritedBoundaryDataSource = false;
		this.datatable1.InheritedDataSource = false;
		this.datatable1.InheritedBoundaryDataSource = false;
		// Container child datatable1.Gtk.Table+TableChild
		this.dataentry1 = new global::Gtk.DataBindings.DataEntry ();
		this.dataentry1.CanFocus = true;
		this.dataentry1.Name = "dataentry1";
		this.dataentry1.IsEditable = true;
		this.dataentry1.InvisibleChar = '•';
		this.dataentry1.InheritedDataSource = true;
		this.dataentry1.Mappings = "Name";
		this.dataentry1.InheritedBoundaryDataSource = false;
		this.dataentry1.InheritedDataSource = true;
		this.dataentry1.Mappings = "Name";
		this.dataentry1.InheritedBoundaryDataSource = false;
		this.datatable1.Add (this.dataentry1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry1]));
		w1.LeftAttach = ((uint)(1));
		w1.RightAttach = ((uint)(2));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.dataentry2 = new global::Gtk.DataBindings.DataEntry ();
		this.dataentry2.CanFocus = true;
		this.dataentry2.Name = "dataentry2";
		this.dataentry2.IsEditable = true;
		this.dataentry2.InvisibleChar = '•';
		this.dataentry2.InheritedDataSource = true;
		this.dataentry2.Mappings = "LastName";
		this.dataentry2.InheritedBoundaryDataSource = false;
		this.dataentry2.InheritedDataSource = true;
		this.dataentry2.Mappings = "LastName";
		this.dataentry2.InheritedBoundaryDataSource = false;
		this.datatable1.Add (this.dataentry2);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataentry2]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.dataexpander1 = new global::Gtk.DataBindings.DataExpander (null);
		this.dataexpander1.CanFocus = true;
		this.dataexpander1.Name = "dataexpander1";
		this.dataexpander1.Expanded = true;
		this.dataexpander1.InheritedDataSource = true;
		this.dataexpander1.InheritedBoundaryDataSource = false;
		this.dataexpander1.InheritedDataSource = true;
		this.dataexpander1.InheritedBoundaryDataSource = false;
		// Container child dataexpander1.Gtk.Container+ContainerChild
		this.datacalendar1 = new global::Gtk.DataBindings.DataCalendar ();
		this.datacalendar1.CanFocus = true;
		this.datacalendar1.Name = "datacalendar1";
		this.datacalendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(3));
		this.datacalendar1.InheritedDataSource = true;
		this.datacalendar1.Mappings = "BirthDate";
		this.datacalendar1.InheritedBoundaryDataSource = false;
		this.datacalendar1.InheritedDataSource = true;
		this.datacalendar1.Mappings = "BirthDate";
		this.datacalendar1.InheritedBoundaryDataSource = false;
		this.dataexpander1.Add (this.datacalendar1);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("Select Date");
		this.GtkLabel4.UseUnderline = true;
		this.dataexpander1.LabelWidget = this.GtkLabel4;
		this.datatable1.Add (this.dataexpander1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.dataexpander1]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		// Container child datatable1.Gtk.Table+TableChild
		this.datalabel1 = new global::Gtk.DataBindings.DataLabel ();
		this.datalabel1.Name = "datalabel1";
		this.datalabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("datalabel1");
		this.datalabel1.InheritedDataSource = true;
		this.datalabel1.Mappings = "FullName";
		this.datalabel1.InheritedBoundaryDataSource = false;
		this.datalabel1.Important = false;
		this.datalabel1.InheritedDataSource = true;
		this.datalabel1.Mappings = "FullName";
		this.datalabel1.InheritedBoundaryDataSource = false;
		this.datatable1.Add (this.datalabel1);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.datalabel1]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Date of Birth");
		this.datatable1.Add (this.label1);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label1]));
		w6.TopAttach = ((uint)(3));
		w6.BottomAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("First Name");
		this.datatable1.Add (this.label4);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label4]));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Full Name");
		this.datatable1.Add (this.label5);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label5]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child datatable1.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Last Name");
		this.datatable1.Add (this.label6);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.datatable1 [this.label6]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.datatable1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.datatable1]));
		w10.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		this.hbox1.BorderWidth = ((uint)(6));
		// Container child hbox1.Gtk.Box+BoxChild
		this.checkbutton1 = new global::Gtk.CheckButton ();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Show cursored data");
		this.checkbutton1.Active = true;
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.hbox1.Add (this.checkbutton1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkbutton1]));
		w11.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Add click");
		this.hbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Swap person");
		this.hbox1.Add (this.button2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Close");
		this.hbox1.Add (this.button3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button3]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w15.PackType = ((global::Gtk.PackType)(1));
		w15.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 449;
		this.DefaultHeight = 427;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.checkbutton1.Activated += new global::System.EventHandler (this.OnCheckbutton1Activated);
		this.checkbutton1.Clicked += new global::System.EventHandler (this.OnCheckbutton1Activated);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
