// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.DataBindings.DataTable datatable1;
    
    private Gtk.DataBindings.DataEntry dataentry1;
    
    private Gtk.DataBindings.DataEntry dataentry2;
    
    private Gtk.DataBindings.DataExpander dataexpander1;
    
    private Gtk.DataBindings.DataCalendar datacalendar1;
    
    private Gtk.Label GtkLabel4;
    
    private Gtk.DataBindings.DataLabel datalabel1;
    
    private Gtk.Label label1;
    
    private Gtk.Label label4;
    
    private Gtk.Label label5;
    
    private Gtk.Label label6;
    
    private Gtk.HBox hbox1;
    
    private Gtk.CheckButton checkbutton1;
    
    private Gtk.Button button1;
    
    private Gtk.Button button2;
    
    private Gtk.Button button3;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 4;
        this.vbox1.BorderWidth = ((uint)(4));
        // Container child vbox1.Gtk.Box+BoxChild
        this.datatable1 = new Gtk.DataBindings.DataTable(((uint)(4)), ((uint)(2)), false);
        this.datatable1.Name = "datatable1";
        this.datatable1.RowSpacing = ((uint)(4));
        this.datatable1.ColumnSpacing = ((uint)(8));
        this.datatable1.BorderWidth = ((uint)(4));
        this.datatable1.InheritedDataSource = false;
        this.datatable1.InheritedBoundaryDataSource = false;
        // Container child datatable1.Gtk.Table+TableChild
        this.dataentry1 = new Gtk.DataBindings.DataEntry();
        this.dataentry1.CanFocus = true;
        this.dataentry1.Name = "dataentry1";
        this.dataentry1.IsEditable = true;
        this.dataentry1.InvisibleChar = '•';
        this.dataentry1.InheritedDataSource = true;
        this.dataentry1.Mappings = "Name";
        this.dataentry1.InheritedBoundaryDataSource = false;
        this.datatable1.Add(this.dataentry1);
        Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry1]));
        w1.LeftAttach = ((uint)(1));
        w1.RightAttach = ((uint)(2));
        w1.YOptions = ((Gtk.AttachOptions)(4));
        // Container child datatable1.Gtk.Table+TableChild
        this.dataentry2 = new Gtk.DataBindings.DataEntry();
        this.dataentry2.CanFocus = true;
        this.dataentry2.Name = "dataentry2";
        this.dataentry2.IsEditable = true;
        this.dataentry2.InvisibleChar = '•';
        this.dataentry2.InheritedDataSource = true;
        this.dataentry2.Mappings = "LastName";
        this.dataentry2.InheritedBoundaryDataSource = false;
        this.datatable1.Add(this.dataentry2);
        Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry2]));
        w2.TopAttach = ((uint)(1));
        w2.BottomAttach = ((uint)(2));
        w2.LeftAttach = ((uint)(1));
        w2.RightAttach = ((uint)(2));
        w2.YOptions = ((Gtk.AttachOptions)(4));
        // Container child datatable1.Gtk.Table+TableChild
        this.dataexpander1 = new Gtk.DataBindings.DataExpander(null);
        this.dataexpander1.CanFocus = true;
        this.dataexpander1.Name = "dataexpander1";
        this.dataexpander1.Expanded = true;
        this.dataexpander1.InheritedDataSource = true;
        this.dataexpander1.InheritedBoundaryDataSource = false;
        // Container child dataexpander1.Gtk.Container+ContainerChild
        this.datacalendar1 = new Gtk.DataBindings.DataCalendar();
        this.datacalendar1.CanFocus = true;
        this.datacalendar1.Name = "datacalendar1";
        this.datacalendar1.DisplayOptions = ((Gtk.CalendarDisplayOptions)(3));
        this.datacalendar1.InheritedDataSource = true;
        this.datacalendar1.Mappings = "BirthDate";
        this.datacalendar1.InheritedBoundaryDataSource = false;
        this.dataexpander1.Add(this.datacalendar1);
        this.GtkLabel4 = new Gtk.Label();
        this.GtkLabel4.Name = "GtkLabel4";
        this.GtkLabel4.LabelProp = Mono.Unix.Catalog.GetString("Select Date");
        this.GtkLabel4.UseUnderline = true;
        this.dataexpander1.LabelWidget = this.GtkLabel4;
        this.datatable1.Add(this.dataexpander1);
        Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.datatable1[this.dataexpander1]));
        w4.TopAttach = ((uint)(3));
        w4.BottomAttach = ((uint)(4));
        w4.LeftAttach = ((uint)(1));
        w4.RightAttach = ((uint)(2));
        // Container child datatable1.Gtk.Table+TableChild
        this.datalabel1 = new Gtk.DataBindings.DataLabel();
        this.datalabel1.Name = "datalabel1";
        this.datalabel1.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
        this.datalabel1.InheritedDataSource = true;
        this.datalabel1.Mappings = "FullName";
        this.datalabel1.InheritedBoundaryDataSource = false;
        this.datatable1.Add(this.datalabel1);
        Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.datatable1[this.datalabel1]));
        w5.TopAttach = ((uint)(2));
        w5.BottomAttach = ((uint)(3));
        w5.LeftAttach = ((uint)(1));
        w5.RightAttach = ((uint)(2));
        w5.YOptions = ((Gtk.AttachOptions)(4));
        // Container child datatable1.Gtk.Table+TableChild
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.Xalign = 0F;
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("Date of Birth");
        this.datatable1.Add(this.label1);
        Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.datatable1[this.label1]));
        w6.TopAttach = ((uint)(3));
        w6.BottomAttach = ((uint)(4));
        w6.XOptions = ((Gtk.AttachOptions)(4));
        w6.YOptions = ((Gtk.AttachOptions)(4));
        // Container child datatable1.Gtk.Table+TableChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.Xalign = 0F;
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("First Name");
        this.datatable1.Add(this.label4);
        Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.datatable1[this.label4]));
        w7.XOptions = ((Gtk.AttachOptions)(4));
        w7.YOptions = ((Gtk.AttachOptions)(4));
        // Container child datatable1.Gtk.Table+TableChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.Xalign = 0F;
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("Full Name");
        this.datatable1.Add(this.label5);
        Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.datatable1[this.label5]));
        w8.TopAttach = ((uint)(2));
        w8.BottomAttach = ((uint)(3));
        w8.XOptions = ((Gtk.AttachOptions)(4));
        w8.YOptions = ((Gtk.AttachOptions)(4));
        // Container child datatable1.Gtk.Table+TableChild
        this.label6 = new Gtk.Label();
        this.label6.Name = "label6";
        this.label6.Xalign = 0F;
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("Last Name");
        this.datatable1.Add(this.label6);
        Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.datatable1[this.label6]));
        w9.TopAttach = ((uint)(1));
        w9.BottomAttach = ((uint)(2));
        w9.XOptions = ((Gtk.AttachOptions)(4));
        w9.YOptions = ((Gtk.AttachOptions)(4));
        this.vbox1.Add(this.datatable1);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox1[this.datatable1]));
        w10.Position = 0;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        this.hbox1.BorderWidth = ((uint)(6));
        // Container child hbox1.Gtk.Box+BoxChild
        this.checkbutton1 = new Gtk.CheckButton();
        this.checkbutton1.CanFocus = true;
        this.checkbutton1.Name = "checkbutton1";
        this.checkbutton1.Label = Mono.Unix.Catalog.GetString("Show cursored data");
        this.checkbutton1.Active = true;
        this.checkbutton1.DrawIndicator = true;
        this.checkbutton1.UseUnderline = true;
        this.hbox1.Add(this.checkbutton1);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.checkbutton1]));
        w11.Position = 0;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("Add click");
        this.hbox1.Add(this.button1);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.button1]));
        w12.Position = 1;
        w12.Expand = false;
        w12.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("Swap person");
        this.hbox1.Add(this.button2);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox1[this.button2]));
        w13.Position = 2;
        w13.Expand = false;
        w13.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button3 = new Gtk.Button();
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseUnderline = true;
        this.button3.Label = Mono.Unix.Catalog.GetString("Close");
        this.hbox1.Add(this.button3);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox1[this.button3]));
        w14.Position = 3;
        w14.Expand = false;
        w14.Fill = false;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w15.PackType = ((Gtk.PackType)(1));
        w15.Position = 1;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 449;
        this.DefaultHeight = 427;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.checkbutton1.Activated += new System.EventHandler(this.OnCheckbutton1Activated);
        this.checkbutton1.Clicked += new System.EventHandler(this.OnCheckbutton1Activated);
        this.button1.Clicked += new System.EventHandler(this.OnButton3Clicked);
        this.button2.Clicked += new System.EventHandler(this.OnButton2Clicked);
        this.button3.Clicked += new System.EventHandler(this.OnButton1Clicked);
    }
}
