// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace sample3 {
    
    
    public partial class CursoredDataWindow {
        
        private Gtk.DataBindings.DataTable datatable1;
        
        private Gtk.DataBindings.DataLabel datalabel1;
        
        private Gtk.DataBindings.DataLabel datalabel2;
        
        private Gtk.DataBindings.DataLabel datalabel3;
        
        private Gtk.DataBindings.DataLabel datalabel4;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget sample3.CursoredDataWindow
            this.Name = "sample3.CursoredDataWindow";
            this.Title = Mono.Unix.Catalog.GetString("Cursored Data");
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            this.AllowShrink = true;
            this.Decorated = false;
            // Container child sample3.CursoredDataWindow.Gtk.Container+ContainerChild
            this.datatable1 = new Gtk.DataBindings.DataTable(((uint)(5)), ((uint)(2)), false);
            this.datatable1.Name = "datatable1";
            this.datatable1.RowSpacing = ((uint)(4));
            this.datatable1.ColumnSpacing = ((uint)(8));
            this.datatable1.BorderWidth = ((uint)(8));
            this.datatable1.InheritedDataSource = false;
            this.datatable1.InheritedBoundaryDataSource = false;
            // Container child datatable1.Gtk.Table+TableChild
            this.datalabel1 = new Gtk.DataBindings.DataLabel();
            this.datalabel1.Name = "datalabel1";
            this.datalabel1.Xalign = 0F;
            this.datalabel1.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
            this.datalabel1.InheritedDataSource = true;
            this.datalabel1.Mappings = "Name";
            this.datalabel1.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.datalabel1);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.datatable1[this.datalabel1]));
            w1.TopAttach = ((uint)(1));
            w1.BottomAttach = ((uint)(2));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.datalabel2 = new Gtk.DataBindings.DataLabel();
            this.datalabel2.Name = "datalabel2";
            this.datalabel2.Xalign = 0F;
            this.datalabel2.LabelProp = Mono.Unix.Catalog.GetString("datalabel2");
            this.datalabel2.InheritedDataSource = true;
            this.datalabel2.Mappings = "LastName";
            this.datalabel2.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.datalabel2);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.datatable1[this.datalabel2]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.datalabel3 = new Gtk.DataBindings.DataLabel();
            this.datalabel3.Name = "datalabel3";
            this.datalabel3.Xalign = 0F;
            this.datalabel3.LabelProp = Mono.Unix.Catalog.GetString("datalabel3");
            this.datalabel3.InheritedDataSource = true;
            this.datalabel3.Mappings = "FullName";
            this.datalabel3.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.datalabel3);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.datatable1[this.datalabel3]));
            w3.TopAttach = ((uint)(3));
            w3.BottomAttach = ((uint)(4));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.datalabel4 = new Gtk.DataBindings.DataLabel();
            this.datalabel4.Name = "datalabel4";
            this.datalabel4.Xalign = 0F;
            this.datalabel4.LabelProp = Mono.Unix.Catalog.GetString("datalabel4");
            this.datalabel4.InheritedDataSource = true;
            this.datalabel4.Mappings = "BirthDate";
            this.datalabel4.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.datalabel4);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.datatable1[this.datalabel4]));
            w4.TopAttach = ((uint)(4));
            w4.BottomAttach = ((uint)(5));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("First Name");
            this.datatable1.Add(this.label1);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.datatable1[this.label1]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Last Name");
            this.datatable1.Add(this.label2);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.datatable1[this.label2]));
            w6.TopAttach = ((uint)(2));
            w6.BottomAttach = ((uint)(3));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Full Name");
            this.datatable1.Add(this.label3);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.datatable1[this.label3]));
            w7.TopAttach = ((uint)(3));
            w7.BottomAttach = ((uint)(4));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Date of Birth");
            this.datatable1.Add(this.label4);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.datatable1[this.label4]));
            w8.TopAttach = ((uint)(4));
            w8.BottomAttach = ((uint)(5));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.datatable1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 151;
            this.Show();
        }
    }
}
