
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.DataBindings.DataTreeView datatreeview1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.datatreeview1 = new global::Gtk.DataBindings.DataTreeView ();
		this.datatreeview1.CanFocus = true;
		this.datatreeview1.Name = "datatreeview1";
		this.datatreeview1.CursorPointsEveryType = false;
		this.datatreeview1.InheritedDataSource = false;
		this.datatreeview1.Mappings = "";
		this.datatreeview1.InheritedBoundaryDataSource = false;
		this.datatreeview1.InheritedDataSource = false;
		this.datatreeview1.Mappings = "";
		this.datatreeview1.InheritedBoundaryDataSource = false;
		this.datatreeview1.ColumnMappings = "{sample4.PictureInfoClass} Preview[Preview]<<; Name[File Name]<<; Size[Size]<<";
		this.GtkScrolledWindow.Add (this.datatreeview1);
		this.Add (this.GtkScrolledWindow);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 517;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
