// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.VBox vbox1;
    
    private Gtk.Button button1;
    
    private Gtk.DataBindings.DataLabel datalabel1;
    
    private Gtk.DataBindings.DateEntry dateentry1;
    
    private Gtk.DataBindings.DateEntry dateentry2;
    
    private Gtk.Entry entry1;
    
    private Gtk.CheckButton checkbutton1;
    
    private Gtk.Button button2;
    
    private Gtk.Image image303;
    
    private Gtk.ExtraWidgets.IPv4Entry ipv4entry1;
    
    private Gtk.ExtraWidgets.TimeEntry timeentry1;
    
    private Gtk.CheckButton checkbutton2;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        // Container child button1.Gtk.Container+ContainerChild
        Gtk.Alignment w1 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        Gtk.HBox w2 = new Gtk.HBox();
        w2.Spacing = 2;
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Image w3 = new Gtk.Image();
        w2.Add(w3);
        // Container child GtkHBox.Gtk.Container+ContainerChild
        Gtk.Label w5 = new Gtk.Label();
        w5.LabelProp = Mono.Unix.Catalog.GetString("button1");
        w5.UseUnderline = true;
        w2.Add(w5);
        w1.Add(w2);
        this.button1.Add(w1);
        this.vbox1.Add(this.button1);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox1[this.button1]));
        w9.Position = 0;
        w9.Expand = false;
        w9.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.datalabel1 = new Gtk.DataBindings.DataLabel();
        this.datalabel1.Name = "datalabel1";
        this.datalabel1.LabelProp = Mono.Unix.Catalog.GetString("datalabel1");
        this.datalabel1.InheritedDataSource = false;
        this.datalabel1.InheritedBoundaryDataSource = false;
        this.datalabel1.Important = false;
        this.vbox1.Add(this.datalabel1);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox1[this.datalabel1]));
        w10.Position = 1;
        w10.Expand = false;
        w10.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.dateentry1 = new Gtk.DataBindings.DateEntry();
        this.dateentry1.CanFocus = true;
        this.dateentry1.Name = "dateentry1";
        this.dateentry1.HasDropDown = true;
        this.dateentry1.HasClearButton = true;
        this.dateentry1.HasCalculator = true;
        this.dateentry1.Editable = true;
        this.vbox1.Add(this.dateentry1);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox1[this.dateentry1]));
        w11.Position = 3;
        w11.Expand = false;
        w11.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.dateentry2 = new Gtk.DataBindings.DateEntry();
        this.dateentry2.CanFocus = true;
        this.dateentry2.Name = "dateentry2";
        this.dateentry2.HasDropDown = true;
        this.dateentry2.HasClearButton = true;
        this.dateentry2.HasCalculator = true;
        this.dateentry2.Editable = true;
        this.vbox1.Add(this.dateentry2);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.dateentry2]));
        w12.Position = 4;
        w12.Expand = false;
        w12.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.entry1 = new Gtk.Entry();
        this.entry1.CanFocus = true;
        this.entry1.Name = "entry1";
        this.entry1.IsEditable = true;
        this.entry1.InvisibleChar = '•';
        this.vbox1.Add(this.entry1);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox1[this.entry1]));
        w13.Position = 5;
        w13.Expand = false;
        w13.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.checkbutton1 = new Gtk.CheckButton();
        this.checkbutton1.CanFocus = true;
        this.checkbutton1.Name = "checkbutton1";
        this.checkbutton1.Label = Mono.Unix.Catalog.GetString("checkbutton1");
        this.checkbutton1.Active = true;
        this.checkbutton1.DrawIndicator = true;
        this.checkbutton1.UseUnderline = true;
        this.vbox1.Add(this.checkbutton1);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox1[this.checkbutton1]));
        w14.Position = 6;
        w14.Expand = false;
        w14.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("button1");
        this.vbox1.Add(this.button2);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox1[this.button2]));
        w15.Position = 7;
        w15.Expand = false;
        w15.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.image303 = new Gtk.Image();
        this.image303.Name = "image303";
        this.vbox1.Add(this.image303);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox1[this.image303]));
        w16.Position = 8;
        w16.Expand = false;
        w16.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.ipv4entry1 = new Gtk.ExtraWidgets.IPv4Entry();
        this.ipv4entry1.Name = "ipv4entry1";
        this.vbox1.Add(this.ipv4entry1);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox1[this.ipv4entry1]));
        w17.Position = 9;
        w17.Expand = false;
        w17.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.timeentry1 = new Gtk.ExtraWidgets.TimeEntry();
        this.timeentry1.Name = "timeentry1";
        this.timeentry1.Editable = true;
        this.timeentry1.HasDropDown = true;
        this.timeentry1.HasClearButton = true;
        this.timeentry1.HasCalculator = true;
        this.timeentry1.EditSeconds = true;
        this.timeentry1.EditMilliseconds = true;
        this.vbox1.Add(this.timeentry1);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox1[this.timeentry1]));
        w18.Position = 10;
        w18.Expand = false;
        w18.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.checkbutton2 = new Gtk.CheckButton();
        this.checkbutton2.CanFocus = true;
        this.checkbutton2.Name = "checkbutton2";
        this.checkbutton2.Label = Mono.Unix.Catalog.GetString("checkbutton1");
        this.checkbutton2.Active = true;
        this.checkbutton2.DrawIndicator = true;
        this.checkbutton2.UseUnderline = true;
        this.vbox1.Add(this.checkbutton2);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox1[this.checkbutton2]));
        w19.Position = 11;
        w19.Expand = false;
        w19.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 400;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
        this.checkbutton1.Toggled += new System.EventHandler(this.OnCheckbutton1Toggled);
        this.button2.Clicked += new System.EventHandler(this.OnButton2Clicked);
        this.checkbutton2.Toggled += new System.EventHandler(this.OnCheckbutton2Toggled);
    }
}
