// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace dbsample1 {
    
    
    public partial class ConnectionDialog {
        
        private Gtk.VBox vbox3;
        
        private Gtk.DataBindings.DataTable datatable1;
        
        private Gtk.DataBindings.DataEntry dataentry1;
        
        private Gtk.DataBindings.DataEntry dataentry2;
        
        private Gtk.DataBindings.DataEntry dataentry3;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget dbsample1.ConnectionDialog
            this.Name = "dbsample1.ConnectionDialog";
            this.Title = Mono.Unix.Catalog.GetString("Connect");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            this.HasSeparator = false;
            // Internal child dbsample1.ConnectionDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(8));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.datatable1 = new Gtk.DataBindings.DataTable(((uint)(3)), ((uint)(2)), false);
            this.datatable1.Name = "datatable1";
            this.datatable1.RowSpacing = ((uint)(6));
            this.datatable1.ColumnSpacing = ((uint)(8));
            this.datatable1.BorderWidth = ((uint)(5));
            this.datatable1.InheritedDataSource = false;
            this.datatable1.InheritedBoundaryDataSource = false;
            // Container child datatable1.Gtk.Table+TableChild
            this.dataentry1 = new Gtk.DataBindings.DataEntry();
            this.dataentry1.WidthRequest = 200;
            this.dataentry1.CanFocus = true;
            this.dataentry1.Name = "dataentry1";
            this.dataentry1.IsEditable = true;
            this.dataentry1.InvisibleChar = '•';
            this.dataentry1.InheritedDataSource = true;
            this.dataentry1.Mappings = "Server";
            this.dataentry1.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.dataentry1);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry1]));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.dataentry2 = new Gtk.DataBindings.DataEntry();
            this.dataentry2.CanFocus = true;
            this.dataentry2.Name = "dataentry2";
            this.dataentry2.IsEditable = true;
            this.dataentry2.InvisibleChar = '•';
            this.dataentry2.InheritedDataSource = true;
            this.dataentry2.Mappings = "Username";
            this.dataentry2.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.dataentry2);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry2]));
            w3.TopAttach = ((uint)(1));
            w3.BottomAttach = ((uint)(2));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.dataentry3 = new Gtk.DataBindings.DataEntry();
            this.dataentry3.CanFocus = true;
            this.dataentry3.Name = "dataentry3";
            this.dataentry3.IsEditable = true;
            this.dataentry3.Visibility = false;
            this.dataentry3.InvisibleChar = '•';
            this.dataentry3.InheritedDataSource = true;
            this.dataentry3.Mappings = "Password";
            this.dataentry3.InheritedBoundaryDataSource = false;
            this.datatable1.Add(this.dataentry3);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.datatable1[this.dataentry3]));
            w4.TopAttach = ((uint)(2));
            w4.BottomAttach = ((uint)(3));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Server");
            this.datatable1.Add(this.label1);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.datatable1[this.label1]));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Username");
            this.datatable1.Add(this.label2);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.datatable1[this.label2]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child datatable1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Password");
            this.datatable1.Add(this.label3);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.datatable1[this.label3]));
            w7.TopAttach = ((uint)(2));
            w7.BottomAttach = ((uint)(3));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox3.Add(this.datatable1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox3[this.datatable1]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox3.Add(this.hseparator1);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            w1.Add(this.vbox3);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(w1[this.vbox3]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Internal child dbsample1.ConnectionDialog.ActionArea
            Gtk.HButtonBox w11 = this.ActionArea;
            w11.Name = "dialog1_ActionArea";
            w11.Spacing = 6;
            w11.BorderWidth = ((uint)(5));
            w11.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseUnderline = true;
            // Container child buttonOk.Gtk.Container+ContainerChild
            Gtk.Alignment w12 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w13 = new Gtk.HBox();
            w13.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w14 = new Gtk.Image();
            w14.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-connect", Gtk.IconSize.Menu, 16);
            w13.Add(w14);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w16 = new Gtk.Label();
            w16.LabelProp = Mono.Unix.Catalog.GetString("_Connect");
            w16.UseUnderline = true;
            w13.Add(w16);
            w12.Add(w13);
            this.buttonOk.Add(w12);
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w20 = ((Gtk.ButtonBox.ButtonBoxChild)(w11[this.buttonOk]));
            w20.Expand = false;
            w20.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 196;
            this.Show();
        }
    }
}
