// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action MenuAction;
    
    private Gtk.HBox hbox1;
    
    private Gtk.ScrolledWindow GtkScrolledWindow;
    
    private Gtk.DataBindings.DataTreeView datatreeview1;
    
    private Gtk.VButtonBox vbuttonbox1;
    
    private Gtk.Button button107;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.MenuAction = new Gtk.Action("MenuAction", Mono.Unix.Catalog.GetString("Menu"), null, null);
        this.MenuAction.ShortLabel = Mono.Unix.Catalog.GetString("Menu");
        w1.Add(this.MenuAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MainWindow");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.GtkScrolledWindow = new Gtk.ScrolledWindow();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.datatreeview1 = new Gtk.DataBindings.DataTreeView();
        this.datatreeview1.CanFocus = true;
        this.datatreeview1.Name = "datatreeview1";
        this.datatreeview1.URIDragInSupport = false;
        this.datatreeview1.CursorPointsEveryType = false;
        this.datatreeview1.InheritedDataSource = false;
        this.datatreeview1.InheritedBoundaryDataSource = false;
        this.datatreeview1.ColumnMappings = "{System.Data.DataRowView} ID; string_data[string_data]<<; integer_data[integer_data]<<; float_data[float_data]<<";
        this.GtkScrolledWindow.Add(this.datatreeview1);
        this.hbox1.Add(this.GtkScrolledWindow);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
        w3.Position = 0;
        // Container child hbox1.Gtk.Box+BoxChild
        this.vbuttonbox1 = new Gtk.VButtonBox();
        this.vbuttonbox1.Name = "vbuttonbox1";
        // Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
        this.button107 = new Gtk.Button();
        this.button107.CanFocus = true;
        this.button107.Name = "button107";
        this.button107.UseUnderline = true;
        this.button107.Label = Mono.Unix.Catalog.GetString("button107");
        this.vbuttonbox1.Add(this.button107);
        Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.button107]));
        w4.Expand = false;
        w4.Fill = false;
        this.hbox1.Add(this.vbuttonbox1);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox1]));
        w5.Position = 1;
        w5.Expand = false;
        w5.Fill = false;
        this.Add(this.hbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 672;
        this.DefaultHeight = 300;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
    }
}
